(function(){
'use strict';
const model=window.aryAnalysis93,today=()=>model.iso(new Date()),hidden=()=>!!window.aryHidden72?.();
let tab='spending',period='month',anchor=today(),includePayments=true,months=6;
const colors=['#40d5c7','#9685ff','#ffae73','#70baff','#f887b3','#d4c66e'];
const previous=d=>{const x=model.date(d);x.setDate(x.getDate()-1);return model.iso(x)};
const fmt=d=>model.date(d).toLocaleDateString(s.locale||'es-US',{day:'numeric',month:'short',year:'numeric'});
const card=(title,content)=>`<section class="card analysisCard93"><h2>${title}</h2>${content}</section>`;
const empty=text=>`<p class="muted analysisEmpty93">${text}</p>`;
const buttons=(items,current,fn)=>`<div class="analysisTabs93">${items.map(([v,label])=>`<button type="button" class="btn ${String(v)===String(current)?'on':''}" aria-pressed="${String(v)===String(current)}" onclick="${fn}('${v}')">${label}</button>`).join('')}</div>`;
const metrics=items=>`<div class="analysisMetrics93">${items.map(([name,value])=>`<div><span>${name}</span><strong>${money(value)}</strong></div>`).join('')}</div>`;
function bars(data){if(hidden())return empty('Gráficos ocultos por privacidad.');if(!data.bins.some(b=>b.income||b.spent))return empty('Todavía no hay movimientos registrados en este período.');const max=Math.max(...data.bins.flatMap(b=>[b.income,b.spent]),1);return `<p class="analysisLegend93"><i style="background:${colors[0]}"></i> Ingresos recibidos <i style="background:${colors[1]}"></i> Salidas</p><div class="analysisBars93" role="img" aria-label="Ingresos recibidos y salidas por fecha. El detalle está en la tabla.">${data.bins.map(b=>`<div><div class="analysisBarPair93"><i style="height:${b.income/max*100}%;background:${colors[0]}"></i><i style="height:${b.spent/max*100}%;background:${colors[1]}"></i></div><small>${period==='year'||period==='quarter'?model.date(b.date).toLocaleDateString(s.locale,{month:'short'}):Number(b.date.slice(-2))}</small></div>`).join('')}</div><details><summary>Ver valores por fecha</summary><div class="analysisTable93"><table><thead><tr><th>Fecha</th><th>Ingresos</th><th>Salidas</th></tr></thead><tbody>${data.bins.map(b=>`<tr><td>${fmt(b.date)}</td><td>${money(b.income)}</td><td>${money(b.spent)}</td></tr>`).join('')}</tbody></table></div></details>`}
function breakdown(data){if(hidden())return empty('Categorías y proporciones ocultas por privacidad.');if(!data.spent)return empty('Registra gastos con fecha para ver cómo se distribuyen.');let start=0;const segments=data.categories.map(([name,value],i)=>{const end=start+value/data.spent*100,part=`${colors[i%colors.length]} ${start}% ${end}%`;start=end;return part});return `<div class="analysisCategories93"><div class="analysisDonut93" style="background:conic-gradient(${segments.join(',')})" role="img" aria-label="Distribución de las salidas por categoría; detalle a continuación."><span>Salidas<br><b>${money(data.spent)}</b></span></div><ul>${data.categories.map(([name,value],i)=>`<li><i style="background:${colors[i%colors.length]}"></i><span data-ary-user translate="no">${esc(name)}</span><b>${money(value)}</b><small>${(value/data.spent*100).toFixed(1)}%</small></li>`).join('')}</ul></div>`}
function spending(){const data=model.spending(s,period,anchor,today(),includePayments);return buttons([['week','Semana'],['month','Mes'],['quarter','Trimestre'],['year','Año']],period,'aryPeriod93')+`<div class="analysisPeriod93"><button class="btn" aria-label="Período anterior" onclick="aryShift93(-1)">‹</button><b>${fmt(data.start)} – ${fmt(previous(data.end))}</b><button class="btn" aria-label="Período siguiente" onclick="aryShift93(1)">›</button></div><button class="btn tiny" onclick="aryCurrent93()">Volver al período actual</button>`+card('Tu flujo de dinero',metrics([['Ingresos recibidos',data.income],['Salidas registradas',data.spent],['Balance del período',data.net]])+`<p class="muted">Se cuentan movimientos con fecha hasta hoy. Tu ingreso previsto del presupuesto y los gastos recurrentes pendientes no se suman aquí.</p><label class="analysisCheck93"><input type="checkbox" ${includePayments?'checked':''} onchange="aryIncludePayments93(this.checked)"> Incluir pagos de deuda realizados</label>${data.missing?`<p class="muted">${data.missing} gasto(s) sin fecha válida: edítalos en Gastos para incluirlos.</p>`:''}`+bars(data))+card('¿En qué se fue tu dinero?',breakdown(data))+card('Ingresos recibidos',`<p class="muted">Registra cada cobro real una sola vez. Esto no cambia tu ingreso previsto del presupuesto.</p><button class="btn primary widebtn" onclick="aryEntryForm93('income')">Registrar ingreso recibido</button>`+entryList('income',data.incomeRows))+`<button class="btn widebtn" onclick="go('expenses')">Ver o agregar gastos</button>`}
function trend(history){if(hidden())return empty('Historial oculto por privacidad.');if(!history.length)return empty('Guarda tu primer registro. El historial comienza con datos reales desde ese día.');const values=history.map(x=>x.net),min=Math.min(...values),max=Math.max(...values),spread=max-min||1,start=model.date(history[0].date).getTime(),duration=model.date(history.at(-1).date).getTime()-start||1;const points=history.map(x=>`${20+(model.date(x.date).getTime()-start)/duration*560},${160-(x.net-min)/spread*130}`);const change=history.at(-1).net-history[0].net;return `<p>Cambio entre registros: <b>${money(change)}</b></p><svg class="analysisLine93" viewBox="0 0 600 180" role="img" aria-label="Evolución del patrimonio entre registros guardados"><path d="M20 165 H580" stroke="currentColor" opacity=".15"/><polyline points="${points.join(' ')}" fill="none" stroke="${colors[0]}" stroke-width="3"/>${points.map(p=>{const[x,y]=p.split(',');return `<circle cx="${x}" cy="${y}" r="4" fill="${colors[0]}"/>`}).join('')}</svg><p class="muted">${fmt(history[0].date)} – ${fmt(history.at(-1).date)} · ${history.length} registro(s). La línea une los registros guardados; no estima saldos de días intermedios.</p><details><summary>Ver registros guardados</summary><div class="analysisTable93"><table><thead><tr><th>Fecha</th><th>Bienes</th><th>Deudas</th><th>Patrimonio</th></tr></thead><tbody>${history.map(x=>`<tr><td>${fmt(x.date)}</td><td>${money(x.assets)}</td><td>${money(x.debt)}</td><td>${money(x.net)}</td></tr>`).join('')}</tbody></table></div></details>`}
function wealth(){const w=model.worth(s),h=model.history(s,months,today());return card('Tu patrimonio hoy',metrics([['Bienes y saldos',w.assets],['Deudas actuales',w.debt],['Patrimonio neto',w.net]])+`<p class="muted">Patrimonio = bienes y saldos registrados menos deudas. Actualiza el valor de tus bienes antes de guardar un registro. El ahorro acumulado de tus metas no se suma automáticamente para evitar duplicados.</p><button class="btn primary widebtn" onclick="arySnapshot93()">Guardar patrimonio de hoy</button><small class="muted">Un registro por día y moneda. Guardar otra vez actualiza el de hoy; se conservan hasta 365 registros.</small>`)+card('Evolución del patrimonio',buttons([['1','1M'],['3','3M'],['6','6M'],['12','1A'],['0','Todo']],months,'aryMonths93')+trend(h))+card('Tus bienes y saldos',`<p class="muted">Agrega dinero en cuentas, inversiones u otros bienes por su valor actual. Registra cada bien una sola vez.</p><button class="btn primary widebtn" onclick="aryEntryForm93('asset')">Agregar bien o saldo</button>`+entryList('asset',(s.assets93||[]).filter(x=>x.currency===s.currency)))+`<button class="btn widebtn" onclick="go('debts')">Ver o actualizar deudas</button>`}
function entryList(kind,rows){if(hidden())return empty('Registros ocultos por privacidad.');if(!rows.length)return empty('Todavía no hay registros.');return `<ul class="analysisEntries93">${rows.map(x=>`<li><div><b data-ary-user translate="no">${esc(x.name)}</b><small>${kind==='income'?fmt(x.date):'Valor actual'} · ${money(kind==='income'?x.amount:x.value)}</small></div><button class="btn tiny" onclick="aryEntryForm93('${kind}',${Number(x.id)})" aria-label="Editar registro">Editar</button><button class="btn tiny" onclick="aryDeleteEntry93('${kind}',${Number(x.id)})" aria-label="Eliminar registro">Eliminar</button></li>`).join('')}</ul>`}
screens.analysis=()=>head('Análisis','Conoce tu dinero y sigue tu patrimonio.')+`<div class="analysis93" data-ary-copy><p class="muted">Moneda: ${esc(s.currency)}. Los ingresos y bienes nuevos se guardan en esta moneda. Cambiar la moneda no convierte los valores de gastos y deudas existentes.</p>`+buttons([['spending','Ingresos y gastos'],['wealth','Patrimonio']],tab,'aryTab93')+(tab==='spending'?spending():wealth())+'</div>';
for(const route of ['more','expenses']){const before=screens[route];screens[route]=()=>before()+`<button type="button" class="btn widebtn analysisEntry93" onclick="go('analysis')">📊 Análisis de dinero y patrimonio →</button>`}
window.aryTab93=v=>{tab=v==='wealth'?'wealth':'spending';render()};
window.aryPeriod93=v=>{if(['week','month','quarter','year'].includes(v))period=v;render()};
window.aryShift93=n=>{const d=model.date(model.range(period,anchor).start);if(period==='week')d.setDate(d.getDate()+n*7);else d.setMonth(d.getMonth()+n*(period==='year'?12:period==='quarter'?3:1));anchor=model.iso(d);render()};
window.aryCurrent93=()=>{anchor=today();render()};window.aryIncludePayments93=v=>{includePayments=!!v;render()};window.aryMonths93=v=>{months=[0,1,3,6,12].includes(Number(v))?Number(v):6;render()};
const editable=()=>{if(hidden()){toast('Muestra los valores para editar o guardar registros.');return false}return true};
window.arySnapshot93=()=>{if(!editable())return;s.worthHistory93=model.snapshot(s,today());save();toast('Patrimonio de hoy guardado')};
const key=kind=>kind==='asset'?'assets93':'incomeEntries93';
window.aryEntryForm93=(kind,id=null)=>{if(!editable()||!['asset','income'].includes(kind))return;const item=(s[key(kind)]||[]).find(x=>x.id===id&&x.currency===s.currency)||{};modal(`<section data-ary-copy><h2>${id?'Editar registro':kind==='asset'?'Agregar bien o saldo':'Registrar ingreso recibido'}</h2><p class="muted">${esc(s.currency)} · ${kind==='asset'?'Valor actual, sin duplicar otros bienes.':'Cobro real; no modifica el presupuesto.'}</p><label for="analysisName93">Nombre</label><input id="analysisName93" maxlength="120" value="${esc(item.name||'')}" placeholder="${kind==='asset'?'Cuenta de ahorros, inversión, vehículo…':'Salario, venta, trabajo…'}"><label for="analysisAmount93">${kind==='asset'?'Valor actual':'Importe recibido'}</label><input id="analysisAmount93" type="text" inputmode="decimal" value="${esc(String(item.value??item.amount??''))}" placeholder="0">${kind==='income'?`<label for="analysisDate93">Fecha del cobro</label><input id="analysisDate93" type="date" max="${today()}" value="${esc(item.date||today())}">`:''}<button class="btn primary widebtn" onclick="arySaveEntry93('${kind}',${id===null?'null':Number(id)})">Guardar registro</button><button class="btn widebtn" onclick="closeM()">Cancelar</button></section>`)};
window.arySaveEntry93=(kind,id)=>{if(!editable()||!['asset','income'].includes(kind))return;const name=document.getElementById('analysisName93').value.trim(),value=parseNum(document.getElementById('analysisAmount93').value),date=kind==='income'?document.getElementById('analysisDate93').value:null;if(!name||name.length>120||!Number.isFinite(value)||value<=0||value>1e12||kind==='income'&&(!model.date(date)||date>today()))return toast('Revisa el nombre, el importe positivo y la fecha hasta hoy.');const list=Array.isArray(s[key(kind)])?s[key(kind)]:[],old=list.find(x=>x.id===id&&x.currency===s.currency);if(id!==null&&!old)return toast('Este registro ya no existe.');if(!old&&list.length>=1000)return toast('Has llegado al límite de 1000 registros.');const entry={id:old?.id??Math.max(Date.now(),...list.map(x=>Number(x.id)||0))+1,name,currency:s.currency,...(kind==='asset'?{value}:{amount:value,date})};s[key(kind)]=old?list.map(x=>x===old?entry:x):[...list,entry];closeM();save();toast('Registro guardado')};
window.aryDeleteEntry93=(kind,id)=>{if(!editable()||!['asset','income'].includes(kind)||!confirm('¿Eliminar este registro?'))return;s[key(kind)]=(s[key(kind)]||[]).filter(x=>!(x.id===id&&x.currency===s.currency));save()};
})();
