(()=>{
const T={
'es-US':{title:'Gastos hormiga',sub:'Pequeños gastos, grandes oportunidades.',sum:'Tus pequeños gastos sumaron',month:'este mes',avg:'Promedio diario estimado',save:'Si reduces estos gastos un 50%, podrías ahorrar',debt:'al mes para tu deuda.',quick:'Agregar rápido',other:'Otro valor',detail:'Tus gastos controlables',empty:'Todavía no tienes gastos hormiga. Puedes registrar el primero aquí.',coffee:'Café',snacks:'Snacks',transport:'Uber / Transporte',apps:'Apps / Suscripciones',custom:'Otro',choose:'Elige una categoría',added:'Gasto agregado'},
'en-US':{title:'Small recurring expenses',sub:'Small expenses, big opportunities.',sum:'Your small expenses added up to',month:'this month',avg:'Estimated daily average',save:'If you cut these expenses by 50%, you could save',debt:'per month for your debt.',quick:'Quick add',other:'Other amount',detail:'Your controllable expenses',empty:'You do not have any small recurring expenses yet. Add the first one here.',coffee:'Coffee',snacks:'Snacks',transport:'Uber / Transport',apps:'Apps / Subscriptions',custom:'Other',choose:'Choose a category',added:'Expense added'},
'pt-BR':{title:'Pequenos gastos',sub:'Pequenos gastos, grandes oportunidades.',sum:'Seus pequenos gastos somaram',month:'este mês',avg:'Média diária estimada',save:'Se você reduzir esses gastos em 50%, poderá economizar',debt:'por mês para sua dívida.',quick:'Adicionar rápido',other:'Outro valor',detail:'Seus gastos controláveis',empty:'Você ainda não tem pequenos gastos. Adicione o primeiro aqui.',coffee:'Café',snacks:'Lanches',transport:'Uber / Transporte',apps:'Apps / Assinaturas',custom:'Outro',choose:'Escolha uma categoria',added:'Gasto adicionado'}};
let amount=5,cat='Café';
const tx=()=>T[(typeof s!=='undefined'&&T[s.locale])?s.locale:'es-US'];
const antList=()=>s.expenses.filter(e=>e.cat==='Hormiga');
const esc2=x=>typeof esc==='function'?esc(x):String(x).replace(/[&<>"']/g,'');
function catLabel(name){const t=tx(),n=(name||'').toLowerCase();if(n.includes('caf'))return t.coffee;if(n.includes('snack')||n.includes('gase')||n.includes('papa'))return t.snacks;if(n.includes('uber')||n.includes('transport'))return t.transport;if(n.includes('app')||n.includes('suscrip'))return t.apps;return name||t.custom}
function pigMood(total){if(total<=0)return '🐷';const ratio=total/Math.max(+s.income||1,1);return ratio>.25?'😵‍💫':ratio>.12?'🐽':'🐷'}
function renderAnts(){const t=tx(),list=antList(),total=list.reduce((a,e)=>a+(+e.amount||0),0),daily=total/30,save50=total*.5;return head(t.title,t.sub)+`<section class="card full antHero25"><div class="pig25" aria-hidden="true">${pigMood(total)}</div><span class="muted">${t.sum}</span><div class="kpi">${money(total)} <span class="mini">${t.month}</span></div><div class="antAvg25"><span>${t.avg}</span><b>${money(daily)}</b></div><div class="antInsight25">💡 ${t.save} <b class="good">${money(save50)}</b> ${t.debt}</div></section><section class="card full"><div class="antAmounts25">${[1,2,5,10,20].map(v=>`<button class="btn ${amount===v?'on':''}" onclick="aryAntAmount(${v})">${money(v)}</button>`).join('')}</div><div class="antCats25">${[['Café','☕',t.coffee],['Snacks','🥤',t.snacks],['Uber / Transporte','🚕',t.transport],['Apps / Suscripciones','📱',t.apps]].map(x=>`<button class="btn ${cat===x[0]?'on':''}" onclick="aryAntCat('${x[0]}')">${x[1]} ${x[2]}</button>`).join('')}</div><div class="quickAnt antQuick25"><input id="aryAntCustom" type="number" min="0" step="0.01" inputmode="decimal" placeholder="${t.other}"><button class="btn primary" onclick="aryAddAnt()">＋ ${t.quick}</button></div></section><section class="card full"><b>${t.detail}</b><div class="list">${list.length?list.map(e=>row(iconFor(e.name,e.cat),catLabel(e.name),'Hormiga',money(e.amount),`<button class="btn tiny dangerBtn" onclick="deleteExpense(${e.id})">×</button>`)).join(''):`<p class="muted">${t.empty}</p>`}</div></section>`}
window.aryAntAmount=v=>{amount=v;render()};
window.aryAntCat=v=>{cat=v;render()};
window.aryAddAnt=()=>{const input=document.getElementById('aryAntCustom'),custom=input?Number(input.value):0,val=custom>0?custom:amount;if(!(val>0))return;const names={'Café':'Café','Snacks':'Gaseosas / Snacks','Uber / Transporte':'Uber / Transporte','Apps / Suscripciones':'Apps / Suscripciones'};s.expenses.push({id:Date.now(),name:names[cat]||cat,amount:val,cat:'Hormiga'});save();if(typeof toast==='function')toast(tx().added)};
if(typeof screens!=='undefined')screens.ants=renderAnts;
window.aryAntsV25=renderAnts;
})();