(()=>{
const T={
'es-US':{title:'Gastos hormiga',sub:'Pequeños gastos, grandes oportunidades.',sum:'Tus pequeños gastos sumaron',month:'en tus registros actuales',avg:'Promedio por registro',save:'Si reduces estos gastos un 50%, podrías liberar',debt:'para acelerar tu deuda.',quick:'Agregar rápido',other:'Otro valor',detail:'Tus gastos controlables',empty:'Todavía no tienes gastos hormiga. Puedes registrar el primero aquí.',coffee:'Café',snacks:'Snacks',transport:'Uber / Transporte',apps:'Apps / Suscripciones',custom:'Otro',added:'Gasto agregado',top:'Mayor categoría',impact:'Impacto sobre tus ingresos',low:'Bajo',medium:'Moderado',high:'Alto',count:'registros',challenge:'Reto inteligente',challengeText:'Prueba reducir a la mitad tu categoría más alta. Arydebts mostrará el dinero que podrías redirigir a deuda.',potential:'Ahorro potencial'},
'en-US':{title:'Small recurring expenses',sub:'Small expenses, big opportunities.',sum:'Your small expenses added up to',month:'in your current records',avg:'Average per entry',save:'If you cut these expenses by 50%, you could free up',debt:'to accelerate your debt payoff.',quick:'Quick add',other:'Other amount',detail:'Your controllable expenses',empty:'You do not have any small recurring expenses yet. Add the first one here.',coffee:'Coffee',snacks:'Snacks',transport:'Uber / Transport',apps:'Apps / Subscriptions',custom:'Other',added:'Expense added',top:'Top category',impact:'Impact on your income',low:'Low',medium:'Moderate',high:'High',count:'entries',challenge:'Smart challenge',challengeText:'Try cutting your highest category in half. Arydebts will show what you could redirect to debt.',potential:'Potential savings'},
'pt-BR':{title:'Pequenos gastos',sub:'Pequenos gastos, grandes oportunidades.',sum:'Seus pequenos gastos somaram',month:'nos seus registros atuais',avg:'Média por registro',save:'Se você reduzir esses gastos em 50%, poderá liberar',debt:'para acelerar o pagamento da dívida.',quick:'Adicionar rápido',other:'Outro valor',detail:'Seus gastos controláveis',empty:'Você ainda não tem pequenos gastos. Adicione o primeiro aqui.',coffee:'Café',snacks:'Lanches',transport:'Uber / Transporte',apps:'Apps / Assinaturas',custom:'Outro',added:'Gasto adicionado',top:'Maior categoria',impact:'Impacto na sua renda',low:'Baixo',medium:'Moderado',high:'Alto',count:'registros',challenge:'Desafio inteligente',challengeText:'Tente reduzir pela metade sua maior categoria. Arydebts mostrará o valor que você pode direcionar para a dívida.',potential:'Economia potencial'}};
let amount=5,cat='Café';
const tx=()=>T[(typeof s!=='undefined'&&T[s.locale])?s.locale:'es-US'];
const antList=()=>s.expenses.filter(e=>e.cat==='Hormiga');
function catKey(name){const n=(name||'').toLowerCase();if(n.includes('caf'))return'Café';if(n.includes('snack')||n.includes('gase')||n.includes('papa'))return'Snacks';if(n.includes('uber')||n.includes('transport'))return'Uber / Transporte';if(n.includes('app')||n.includes('suscrip'))return'Apps / Suscripciones';return'Otro'}
function catLabel(name){const t=tx(),k=catKey(name);return k==='Café'?t.coffee:k==='Snacks'?t.snacks:k==='Uber / Transporte'?t.transport:k==='Apps / Suscripciones'?t.apps:name||t.custom}
function pigMood(ratio){return ratio>.25?'😵‍💫':ratio>.12?'🐽':'🐷'}
function stats(list){const total=list.reduce((a,e)=>a+(+e.amount||0),0),groups={};list.forEach(e=>{const k=catKey(e.name);groups[k]=(groups[k]||0)+(+e.amount||0)});const top=Object.entries(groups).sort((a,b)=>b[1]-a[1])[0]||['Otro',0];return{total,groups,top,ratio:total/Math.max(+s.income||1,1)}}
function renderAnts(){const t=tx(),list=antList(),z=stats(list),avg=list.length?z.total/list.length:0,save50=z.total*.5,impact=z.ratio>.25?t.high:z.ratio>.12?t.medium:t.low;return head(t.title,t.sub)+`<section class="card full antHero25"><div class="pig25" aria-hidden="true">${pigMood(z.ratio)}</div><span class="muted">${t.sum}</span><div class="kpi">${money(z.total)} <span class="mini">${t.month}</span></div><div class="antAvg25"><span>${t.avg}</span><b>${money(avg)}</b></div><div class="antInsight25">💡 ${t.save} <b class="good">${money(save50)}</b> ${t.debt}</div></section><section class="antStats26"><div class="card"><span class="muted">${t.top}</span><b>${catLabel(z.top[0])}</b><strong>${money(z.top[1])}</strong></div><div class="card"><span class="muted">${t.impact}</span><b>${impact}</b><strong>${Math.round(z.ratio*100)}%</strong></div></section><section class="card full"><div class="antAmounts25">${[1,2,5,10,20].map(v=>`<button class="btn ${amount===v?'on':''}" onclick="aryAntAmount(${v})">${money(v)}</button>`).join('')}</div><div class="antCats25">${[['Café','☕',t.coffee],['Snacks','🥤',t.snacks],['Uber / Transporte','🚕',t.transport],['Apps / Suscripciones','📱',t.apps]].map(x=>`<button class="btn ${cat===x[0]?'on':''}" onclick="aryAntCat('${x[0]}')">${x[1]} ${x[2]}</button>`).join('')}</div><div class="quickAnt antQuick25"><input id="aryAntCustom" type="number" min="0" step="0.01" inputmode="decimal" placeholder="${t.other}"><button class="btn primary" onclick="aryAddAnt()">＋ ${t.quick}</button></div></section>${z.total>0?`<section class="card full antChallenge26"><b>🎯 ${t.challenge}</b><p>${t.challengeText}</p><div><span>${t.potential}</span><strong class="good">${money(z.top[1]*.5)}</strong></div></section>`:''}<section class="card full"><b>${t.detail} · ${list.length} ${t.count}</b><div class="list">${list.length?list.map(e=>row(iconFor(e.name,e.cat),catLabel(e.name),'Hormiga',money(e.amount),`<button class="btn tiny dangerBtn" onclick="deleteExpense(${e.id})">×</button>`)).join(''):`<p class="muted">${t.empty}</p>`}</div></section>`}
window.aryAntAmount=v=>{amount=v;render()};window.aryAntCat=v=>{cat=v;render()};window.aryAddAnt=()=>{const input=document.getElementById('aryAntCustom'),custom=input?Number(input.value):0,val=custom>0?custom:amount;if(!(val>0))return;const names={'Café':'Café','Snacks':'Gaseosas / Snacks','Uber / Transporte':'Uber / Transporte','Apps / Suscripciones':'Apps / Suscripciones'};s.expenses.push({id:Date.now(),name:names[cat]||cat,amount:val,cat:'Hormiga'});save();if(typeof toast==='function')toast(tx().added)};if(typeof screens!=='undefined')screens.ants=renderAnts;window.aryAntsV25=renderAnts;
})();