const KEY='arydebts-v5',AUTH='arydebts-profile';
const fresh=()=>({currency:'USD',locale:'es-US',income:0,incomeFrequency:'biweekly',goal:'',goals:[],onboarded:false,initialDebt:0,savings:0,debts:[],expenses:[],theme:'dark'});
let s=JSON.parse(localStorage.getItem(KEY)||'null')||fresh(),profile=JSON.parse(localStorage.getItem(AUTH)||'null'),screen=profile?(s.onboarded?'home':'setupGoals'):'welcome',debtFilter='all',expenseFilter='all',selectedGoals=[];
const $=q=>document.querySelector(q),esc=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const money=n=>new Intl.NumberFormat(s.locale||'es-US',{style:'currency',currency:s.currency||'USD',maximumFractionDigits:['COP','CLP','JPY','KRW'].includes(s.currency)?0:2}).format(+n||0);
const currencies=()=>['USD','COP','MXN','EUR','BRL','GBP','CAD','ARS','CLP','PEN','JPY','CHF','AUD','NZD','INR','CNY','KRW','SGD','HKD','SEK','NOK','DKK','PLN','CZK','HUF','RON','TRY','ZAR','AED','SAR','ILS','THB','PHP','IDR','MYR','VND'];
function persist(){localStorage.setItem(KEY,JSON.stringify(s))} function save(){persist();render()}
function totals(){let debt=s.debts.reduce((a,x)=>a+(+x.balance||0),0),exp=s.expenses.reduce((a,x)=>a+(+x.amount||0),0),ants=s.expenses.filter(x=>x.cat==='Hormiga').reduce((a,x)=>a+(+x.amount||0),0),mins=s.debts.reduce((a,x)=>a+(+x.min||0),0);return{debt,exp,ants,mins,free:s.income-exp}}
function logo(){return '<div class="brand">Arydebts<small>Solution ↗</small></div>'} function head(title,sub=''){return '<div class="top"><button class="iconBtn" onclick="back()">‹</button>'+logo()+'<div class="avatar">👤</div></div><div class="hello"><h1>'+title+'</h1>'+(sub?'<div class="muted">'+sub+'</div>':'')+'</div>'}
function welcome(){return '<section class="welcome"><div class="welcomeHero"><div class="welcomeLogo">Arydebts<span>Solution</span></div></div><div class="tagline">Tus deudas hoy, tu libertad mañana.</div><div class="benefits"><div class="benefit"><i>🗂️</i><b>Organiza</b><br><span class="muted">Tus finanzas en un solo lugar.</span></div><div class="benefit"><i>⏱️</i><b>Controla</b><br><span class="muted">Tus gastos y deudas fácilmente.</span></div><div class="benefit"><i>✓</i><b>Cumple</b><br><span class="muted">Alcanza tus metas.</span></div></div><button class="btn primary widebtn" onclick="go(\'signup\')">Comenzar mi cambio　→</button><button class="iconBtn widebtn" onclick="go(\'login\')">¿Ya tengo una cuenta?　<span class="grad">Iniciar sesión</span></button><div class="muted" style="margin:8px">— o continúa con —</div><div class="socials"><button class="btn" onclick="socialDemo(\'Apple\')"></button><button class="btn" onclick="socialDemo(\'Google\')">G</button><button class="btn" onclick="socialDemo(\'Facebook\')">f</button><button class="btn" onclick="socialDemo(\'Instagram\')">◎</button></div></section>'}
function auth(mode){let up=mode==='signup';return '<section class="welcome auth"><button class="back" onclick="go(\'welcome\')">‹ Volver</button>'+logo()+'<h1>'+(up?'Crea tu cuenta':'Bienvenido de nuevo')+'</h1><p class="muted">'+(up?'Empecemos a construir tu libertad financiera.':'Continúa con tu plan financiero.')+'</p>'+(up?'<label>Nombre</label><input id="an" placeholder="¿Cómo quieres que te llamemos?">':'')+'<label>Correo electrónico</label><input id="ae" type="email" placeholder="correo@ejemplo.com"><label>Contraseña</label><input id="ap" type="password" placeholder="••••••••"><button class="btn primary widebtn" onclick="localAuth(\''+mode+'\')">'+(up?'Crear cuenta':'Entrar')+'</button></section>'}
const goals=[['🏠','Comprar casa'],['🚗','Comprar carro'],['✈️','Viajar'],['🎓','Estudiar'],['💍','Casarme'],['👶','Familia'],['🧘','Libertad financiera'],['🏝️','Negocio propio'],['💪','Pagar deudas'],['☀️','Otra meta']];
function setupGoals(){return '<section class="onboard"><div class="top"><button class="back" onclick="go(\'welcome\')">‹ Volver</button><div class="avatar">👤</div></div><div class="progressLine"><i style="width:20%"></i></div><div class="muted">Paso 1 de 5</div><div class="hello"><h1>¿Cuáles son tus<br>metas actuales?</h1><div class="muted">Selecciona una o varias. Puedes agregar las tuyas.</div></div><div class="choiceGrid">'+goals.map(g=>'<button class="btn choice '+(selectedGoals.includes(g[1])?'selected':'')+'" onclick="toggleGoal(\''+g[1]+'\')"><span class="big">'+g[0]+'</span>'+g[1]+'</button>').join('')+'</div><button class="btn primary widebtn" onclick="saveGoals()">Siguiente　→</button></section>'}
function setupIncome(){return onboardHead(2,'¿Cuánto ganas?','Necesitamos saber cuánto dinero entra para crear un plan que sí puedas cumplir.')+'<section class="card"><label>Ingreso habitual</label><input id="oi" type="number" inputmode="decimal" placeholder="0.00"><label>¿Cada cuánto recibes este ingreso?</label><select id="of"><option value="weekly">Cada semana</option><option value="biweekly">Cada 2 semanas</option><option value="monthly">Cada mes</option></select><label>Moneda</label><select id="oc">'+currencies().map(c=>'<option '+(c===s.currency?'selected':'')+'>'+c+'</option>').join('')+'</select><button class="btn primary widebtn" onclick="saveIncomeSetup()">Siguiente　→</button></section>'}
function setupDebts(){return onboardHead(3,'¿Qué deudas tienes?','Agrega tarjetas, carro, préstamos, renta atrasada o cualquier obligación.')+'<div class="list">'+(s.debts.length?s.debts.map(d=>debtRow(d)).join(''):'<section class="card"><b>Aún no agregaste deudas.</b><p class="muted">También está bien. Puedes continuar si no tienes.</p></section>')+'</div><button class="btn primary widebtn" onclick="debtForm(null,true)">＋ Agregar deuda</button><button class="btn widebtn" onclick="go(\'setupExpenses\')">Siguiente　→</button>'}
function setupExpenses(){return onboardHead(4,'¿Cuánto gastas?','Agrega tus gastos necesarios y variables. Después podrás registrar los pequeños gastos del día a día.')+'<div class="list">'+(s.expenses.length?s.expenses.map(e=>expenseRow(e)).join(''):'<section class="card"><b>Empieza por lo esencial.</b><p class="muted">Renta, comida, gasolina, servicios y suscripciones.</p></section>')+'</div><button class="btn primary widebtn" onclick="expenseForm(null,true)">＋ Agregar gasto</button><button class="btn widebtn" onclick="go(\'setupFinish\')">Siguiente　→</button>'}
function setupFinish(){let t=totals();return onboardHead(5,'Tu punto de partida','Ya tenemos lo necesario para empezar. Puedes cambiar cualquier dato después.')+'<section class="card heroCard glow"><div class="grid"><div class="third"><span class="muted">Ingresos</span><div class="kpi">'+money(s.income)+'</div></div><div class="third"><span class="muted">Gastos</span><div class="kpi">'+money(t.exp)+'</div></div><div class="third"><span class="muted">Deudas</span><div class="kpi">'+money(t.debt)+'</div></div></div></section><section class="notice card">🎉 <b>Cada pequeña decisión hace una gran diferencia.</b><p class="muted">Arydebts organizará tu información para mostrarte el siguiente paso.</p></section><button class="btn primary widebtn" onclick="finishOnboarding()">Crear mi plan　→</button>'}
function onboardHead(n,title,sub){return '<section class="onboard"><div class="top"><button class="back" onclick="back()">‹ Volver</button><div class="avatar">👤</div></div><div class="progressLine"><i style="width:'+(n*20)+'%"></i></div><div class="muted">Paso '+n+' de 5</div><div class="hello"><h1>'+title+'</h1><div class="muted">'+sub+'</div></div></section>'}
function home(){let t=totals(),base=s.initialDebt||t.debt||1,p=Math.max(0,Math.min(100,Math.round((1-t.debt/base)*100))),remaining=Math.max(0,t.debt);return '<div class="top"><div></div>'+logo()+'<button class="iconBtn" onclick="go(\'notifications\')">🔔</button></div><div class="hello"><h1>Buenos días<br>¡'+esc(profile?.name||'Comandante')+'! 👋</h1><div class="muted">Hoy es un gran día para acercarte a tus metas.</div></div><section class="card heroCard glow"><b>Tu progreso hacia '+esc(s.goal||'la libertad financiera')+'</b><div class="progressBox"><div class="ring"><b>'+p+'%</b></div><div><span class="muted">Deuda total</span><div class="kpi">'+money(t.debt)+'</div><span class="muted">Restante</span><div style="font-size:20px;font-weight:900">'+money(remaining)+'</div></div></div></section><div class="grid"><section class="card third"><span class="muted">🟢 Ingresos</span><div class="kpi">'+money(s.income)+'</div></section><section class="card third"><span class="muted">🔴 Gastos</span><div class="kpi">'+money(t.exp)+'</div></section><section class="card third"><span class="muted">🔵 Disponible</span><div class="kpi">'+money(t.free)+'</div></section></div><section class="notice card">🎉 Cada pequeña decisión hace una gran diferencia.</section><section><div style="display:flex;justify-content:space-between"><b>Tus próximos pagos</b><button class="iconBtn" onclick="go(\'calendar\')">Ver todos ›</button></div><div class="list">'+s.debts.slice(0,3).map((d,i)=>debtRow(d,true,i)).join('')+'</div></section>'}
function debtRow(d,compact=false,i=0){return '<div class="row"><div class="rowleft"><span class="ico">'+iconFor(d.name,'deuda')+'</span><div><strong>'+esc(d.name)+'</strong><span class="muted">'+(compact?'Próximo pago: '+money(d.min):'Pago mínimo: '+money(d.min)+(d.due?' · Vence: '+esc(d.due):''))+'</span></div></div><div style="text-align:right"><b class="danger">'+money(compact?d.min:d.balance)+'</b>'+(compact?'<div class="tag">'+['En 2 días','En 1 semana','En 3 semanas'][i%3]+'</div>':'<div class="planbar"><i style="width:55%"></i></div>')+'</div></div>'}
function debts(){let list=s.debts.filter(d=>debtFilter==='paid'?d.balance<=0:debtFilter==='active'?d.balance>0:true);return head('Mis deudas')+'<div class="tabs">'+[['all','Todas'],['active','Activas'],['paid','Pagadas']].map(x=>'<button class="'+(debtFilter===x[0]?'on':'')+'" onclick="setDebtFilter(\''+x[0]+'\')">'+x[1]+'</button>').join('')+'</div><div class="list">'+(list.length?list.map(d=>debtRow(d)).join(''):'<section class="card">No hay deudas en esta categoría.</section>')+'</div><button class="btn primary widebtn" onclick="debtForm()">＋ Agregar deuda</button>'}
function expenses(){let list=s.expenses.filter(e=>expenseFilter==='all'||e.cat===expenseFilter);return head('Mis gastos')+'<div class="tabs">'+[['all','Todos'],['Esencial','Necesarios'],['Variable','Variables'],['Hormiga','Hormiga']].map(x=>'<button class="'+(expenseFilter===x[0]?'on':'')+'" onclick="setExpenseFilter(\''+x[0]+'\')">'+x[1]+'</button>').join('')+'</div><div class="list">'+(list.length?list.map(e=>expenseRow(e)).join(''):'<section class="card">No hay gastos aquí todavía.</section>')+'</div><button class="btn primary widebtn" onclick="expenseForm()">＋ Agregar gasto</button>'}
function expenseRow(e){return '<div class="row"><div class="rowleft"><span class="ico">'+iconFor(e.name,e.cat)+'</span><div><strong>'+esc(e.name)+'</strong><span class="muted">'+esc(e.cat)+'</span></div></div><b>'+money(e.amount)+'</b></div>'}
function ants(){let t=totals(),monthly=t.ants*4.33;return head('Gastos hormiga')+'<section class="card" style="background:linear-gradient(120deg,#742743,#7b234d)"><div style="display:flex;gap:12px;align-items:center"><div style="font-size:52px">🐷</div><div><span class="muted">Tus pequeños gastos sumaron</span><div class="kpi">'+money(t.ants)+' <span class="mini">registrados</span></div><div class="mini">≈ '+money(monthly)+' al mes si mantienes el ritmo</div></div></div></section><div class="amountPresets">'+[1,2,5,10,20].map(x=>'<button class="btn" onclick="quickAnt('+x+')">$'+x+'</button>').join('')+'</div><button class="btn primary widebtn" onclick="expenseForm(null,false,\'Hormiga\')">＋ Agregar rápido</button><div class="list">'+s.expenses.filter(e=>e.cat==='Hormiga').map(expenseRow).join('')+'</div><section class="notice card">🐷 Si reduces estos gastos un 50%, podrías liberar <b class="good">'+money(t.ants*.5)+'</b> para tu deuda.</section>'}
function plan(){let t=totals(),extra=Math.max(0,t.free-t.mins),target=[...s.debts].filter(d=>d.balance>0).sort((a,b)=>(b.apr||0)-(a.apr||0))[0];return head('Mi plan','Una guía clara para tu próximo ingreso.')+'<section class="card heroCard"><b>Tu próxima jugada</b><div class="kpi">'+(target?esc(target.name):'Sin deudas activas 🎉')+'</div><p class="muted">'+(target?'Cubre primero tus mínimos. Si queda disponible, dirige '+money(extra)+' adicional a esta deuda.':'Puedes dirigir tu disponible a ahorro y metas.')+'</p></section><div class="list"><div class="row"><b>Ingreso</b><b>'+money(s.income)+'</b></div><div class="row"><b>Gastos registrados</b><b>'+money(t.exp)+'</b></div><div class="row"><b>Mínimos de deuda</b><b>'+money(t.mins)+'</b></div><div class="row"><b>Disponible calculado</b><b class="good">'+money(t.free)+'</b></div></div><button class="btn primary widebtn" onclick="go(\'buy\')">¿Puedo comprar esto?</button>'}
function calendar(){let days=Array.from({length:30},(_,i)=>i+1);return head('Asistente de pagos')+'<section class="card"><div style="text-align:center;font-weight:900">Este mes</div><div class="calendarGrid">'+days.map((d,i)=>'<div class="day '+([12,15,20,25].includes(d)?'pay':'')+'">'+d+'</div>').join('')+'</div></section><b>Próximos pagos</b><div class="list">'+s.debts.map(debtRow).join('')+'</div>'}
function assistant(){return head('Asistente Arydebts')+'<div class="assistantHead"><div class="bot">🤖</div><div><b>Asistente Arydebts</b><div class="muted">En línea • Siempre aquí para ayudarte</div></div></div><div id="chatlog" class="chat" style="margin-top:14px"><div class="bubble">¡Hola! 👋 Soy tu asistente financiero. Puedo ayudarte a entender tus números y organizar el próximo paso.</div></div><div class="list" style="margin-top:10px">'+['¿Cómo puedo reducir mis gastos?','¿Puedo comprar esto?','Dame un plan para pagar mis deudas','¿Cuánto he ahorrado?'].map(q=>'<button class="btn" onclick="ask(\''+q+'\')">'+q+'　→</button>').join('')+'</div><div class="quickAnt" style="margin-top:10px"><input id="chatinput" placeholder="Escribe tu mensaje..."><button class="btn primary" onclick="chat()">➤</button></div>'}
function buy(){return head('¿Puedo comprar esto?','Revisa cómo una compra afectaría tu plan antes de decidir.')+'<section class="card"><label>¿Qué quieres comprar?</label><input id="buyName" placeholder="Ej. Audífonos"><label>Precio</label><input id="buyPrice" type="number" placeholder="0.00"><button class="btn primary widebtn" onclick="checkBuy()">Analizar compra</button><div id="buyResult"></div></section>'}
function more(){return head('Más')+'<div class="menuGrid"><button class="btn" onclick="go(\'assistant\')">🤖 Asistente</button><button class="btn" onclick="go(\'calendar\')">📅 Pagos</button><button class="btn" onclick="go(\'ants\')">🐷 Gastos hormiga</button><button class="btn" onclick="go(\'buy\')">🛍️ ¿Puedo comprar?</button><button class="btn" onclick="incomeForm()">💵 Ingresos</button><button class="btn" onclick="go(\'goals\')">🎯 Metas</button><button class="btn" onclick="logout()">↩ Cerrar sesión</button></div>'}
function goalsPage(){return head('Mis metas')+'<div class="card">'+(s.goals.length?s.goals.map(g=>'<span class="goalChip">🎯 '+esc(g)+'</span>').join(''):'Aún no tienes metas guardadas.')+'</div><button class="btn primary widebtn" onclick="go(\'setupGoals\')">Editar metas</button>'}
function notifications(){return head('Notificaciones')+'<div class="list"><div class="row">🟢 <div><b>Tu plan está listo</b><div class="muted">Revisa tus próximos pagos.</div></div></div><div class="row">💡 <div><b>Consejo Arydebts</b><div class="muted">Registra los gastos pequeños para descubrir fugas de dinero.</div></div></div></div>'}
const screens={welcome,signup:()=>auth('signup'),login:()=>auth('login'),setupGoals,setupIncome,setupDebts,setupExpenses,setupFinish,home,debts,expenses,ants,plan,calendar,assistant,buy,more,goals:goalsPage,notifications};
function render(){document.querySelector('#app').innerHTML=(screens[screen]||home)();let hide=['welcome','signup','login','setupGoals','setupIncome','setupDebts','setupExpenses','setupFinish'];let nav=$('#nav');nav.style.display=hide.includes(screen)?'none':'flex';nav.innerHTML=[['home','⌂','Inicio'],['debts','▣','Deudas'],['expenses','◉','Gastos'],['plan','▤','Plan'],['more','•••','Más']].map(x=>'<button class="'+(screen===x[0]?'active':'')+'" onclick="go(\''+x[0]+'\')"><b>'+x[1]+'</b>'+x[2]+'</button>').join('')}
function go(x){screen=x;history.pushState({screen:x},'','#'+x);render();scrollTo(0,0)} function back(){history.length>1?history.back():go('home')} window.onpopstate=e=>{screen=e.state?.screen||(profile?'home':'welcome');render()};
function localAuth(mode){let e=$('#ae').value.trim(),p=$('#ap').value,n=mode==='signup'?$('#an').value.trim():(profile?.name||'Comandante');if(!e||!p||!n)return toast('Completa todos los campos');profile={name:n,email:e};localStorage.setItem(AUTH,JSON.stringify(profile));if(mode==='signup'){s=fresh();selectedGoals=[];persist();go('setupGoals')}else go(s.onboarded?'home':'setupGoals')}
function socialDemo(x){toast(x+' estará disponible al conectar autenticación real')} function logout(){localStorage.removeItem(AUTH);profile=null;screen='welcome';render()}
function toggleGoal(g){selectedGoals.includes(g)?selectedGoals=selectedGoals.filter(x=>x!==g):selectedGoals.push(g);render()} function saveGoals(){if(!selectedGoals.length)return toast('Selecciona al menos una meta');s.goals=[...selectedGoals];s.goal=selectedGoals[0];persist();go('setupIncome')}
function saveIncomeSetup(){s.income=+$('#oi').value||0;s.incomeFrequency=$('#of').value;s.currency=$('#oc').value;if(s.income<=0)return toast('Escribe cuánto ganas');persist();go('setupDebts')}
function finishOnboarding(){s.onboarded=true;s.initialDebt=totals().debt;persist();go('home')}
function setDebtFilter(x){debtFilter=x;render()} function setExpenseFilter(x){expenseFilter=x;render()}
function iconFor(n,c){let z=(n+' '+c).toLowerCase();return z.includes('tarjeta')?'💳':z.includes('carro')||z.includes('auto')?'🚙':z.includes('tel')||z.includes('cel')?'📱':z.includes('renta')||z.includes('casa')?'🏠':z.includes('gas')?'⛽':z.includes('comida')||z.includes('rest')?'🍴':z.includes('café')?'☕':z.includes('uber')||z.includes('transport')?'🚕':z.includes('snack')||z.includes('gase')?'🥤':'💰'}
function modal(h){$('#modal').innerHTML='<div class="sheet">'+h+'</div>';$('#modal').classList.remove('hidden')} function closeM(){$('#modal').classList.add('hidden')} function toast(x){let t=$('#toast');t.textContent=x;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),1800)} function parseNum(v){return Number(String(v).replace(/[^0-9.,-]/g,'').replace(',','.'))||0}
function debtForm(id=null,onboard=false){let d=s.debts.find(x=>x.id===id)||{};modal('<button class="back" onclick="closeM()">‹ Volver</button><h2>'+(id?'Editar deuda':'Agregar deuda')+'</h2><label>Moneda</label><select id="dc">'+currencies().map(c=>'<option '+(c===s.currency?'selected':'')+'>'+c+'</option>').join('')+'</select><label>Nombre de la deuda</label><input id="dn" value="'+esc(d.name||'')+'" placeholder="Ej: Tarjeta de crédito"><label>Valor total</label><input id="db" inputmode="decimal" value="'+(d.balance??'')+'" placeholder="$ 0.00"><label>Pago mínimo (opcional)</label><input id="dm" inputmode="decimal" value="'+(d.min??'')+'" placeholder="$ 0.00"><label>Interés APR % (opcional)</label><input id="da" inputmode="decimal" value="'+(d.apr??'')+'"><label>Fecha de vencimiento</label><input id="dd" type="date" value="'+esc(d.due||'')+'"><label>Notas (opcional)</label><textarea id="dnotes" placeholder="Banco, últimos 4 dígitos, etc.">'+esc(d.notes||'')+'</textarea><div class="actions"><button class="btn" onclick="closeM()">Cancelar</button><button class="btn primary" style="flex:1" onclick="saveDebt('+(id||'null')+','+onboard+')">Guardar deuda</button></div>')}
function saveDebt(id,onboard){let name=$('#dn').value.trim(),balance=parseNum($('#db').value),min=parseNum($('#dm').value),apr=parseNum($('#da').value),due=$('#dd').value,notes=$('#dnotes').value.trim();if(!name||balance<=0)return toast('Completa nombre y valor total');if(id)Object.assign(s.debts.find(x=>x.id===id),{name,balance,min,apr,due,notes});else s.debts.push({id:Date.now(),name,balance,min,apr,due,notes});closeM();save()}
function expenseForm(id=null,onboard=false,cat='Esencial'){let e=s.expenses.find(x=>x.id===id)||{};modal('<button class="back" onclick="closeM()">‹ Volver</button><h2>'+(id?'Editar gasto':'Agregar gasto')+'</h2><label>Nombre</label><input id="en" value="'+esc(e.name||'')+'" placeholder="Comida, gasolina, café..."><label>Valor</label><input id="eb" inputmode="decimal" value="'+(e.amount??'')+'" placeholder="$ 0.00"><label>Categoría</label><select id="ec">'+['Esencial','Variable','Hormiga'].map(x=>'<option '+((e.cat||cat)===x?'selected':'')+'>'+x+'</option>').join('')+'</select><button class="btn primary widebtn" onclick="saveExpense('+(id||'null')+')">Guardar gasto</button><button class="btn widebtn" onclick="closeM()">Cancelar</button>')}
function saveExpense(id){let name=$('#en').value.trim(),amount=parseNum($('#eb').value),cat=$('#ec').value;if(!name||amount<=0)return toast('Completa nombre y valor');if(id)Object.assign(s.expenses.find(x=>x.id===id),{name,amount,cat});else s.expenses.push({id:Date.now(),name,amount,cat});closeM();save()}
function quickAnt(v){s.expenses.push({id:Date.now(),name:'Gasto rápido',amount:v,cat:'Hormiga'});save();toast('Gasto registrado')}
function incomeForm(){modal('<h2>Editar ingreso</h2><label>Ingreso</label><input id="inc" type="number" value="'+s.income+'"><label>Frecuencia</label><select id="if"><option value="weekly">Semanal</option><option value="biweekly">Cada 2 semanas</option><option value="monthly">Mensual</option></select><button class="btn primary widebtn" onclick="setIncome()">Guardar</button>')} function setIncome(){s.income=+$('#inc').value||0;s.incomeFrequency=$('#if').value;closeM();save()}
function checkBuy(){let p=+$('#buyPrice').value||0,n=$('#buyName').value.trim()||'Esta compra',t=totals(),safe=Math.max(0,t.free-t.mins),ok=p>0&&p<=safe*.25;$('#buyResult').innerHTML='<section class="notice card"><b>'+(ok?'✅ Cabe mejor dentro de tu plan.':'⏳ Conviene esperar.')+'</b><p>'+esc(n)+' cuesta '+money(p)+'. '+(ok?'Aun así, confirma tus pagos próximos antes de comprar.':'Ahora mismo consumiría demasiado de tu margen después de obligaciones.')+'</p></section>'}
function ask(q){let i=$('#chatinput');i.value=q;chat()} function chat(){let i=$('#chatinput'),v=i.value.trim();if(!v)return;let t=totals(),answer=v.toLowerCase().includes('gasto')?'Tus gastos registrados suman '+money(t.exp)+'. Tus gastos hormiga suman '+money(t.ants)+'. Empieza reduciendo una categoría controlable, no todo a la vez.':v.toLowerCase().includes('deuda')?'Tienes '+money(t.debt)+' en deuda registrada y '+money(t.mins)+' en pagos mínimos. Prioriza esenciales y mínimos; luego dirige el extra a la deuda con mayor interés.':'Con tus datos actuales tienes '+money(t.free)+' entre ingreso y gastos registrados. Puedo ayudarte a convertir ese número en un próximo paso.';$('#chatlog').innerHTML+='<div class="bubble me">'+esc(v)+'</div><div class="bubble">'+answer+'</div>';i.value=''}
document.addEventListener('keydown',e=>{if(e.key==='Enter'&&document.activeElement?.id==='chatinput')chat()});render();