window.addEventListener("error",function(e){var a=document.getElementById("app");if(a&&!a.innerHTML){a.innerHTML='<section class="welcome"><h1>Arydebts Solution</h1><p>No pudimos iniciar la aplicación.</p><p class="muted">'+String(e.message||"Error").replace(/[<>]/g,"")+'</p></section>'}});
const KEY="arydebts-v3",AUTH="arydebts-profile",FX="arydebts-fx";
const seed={currency:"USD",locale:"es-US",mode:"immersive",name:"Ana",income:850,incomeFrequency:"weekly",goal:"Salir de deudas",goals:["Vivir sin deudas"],greeting:"Hola",theme:"dark",navOrder:["home","debts","expenses","plan","more"],savings:0,onboarded:false,debts:[{id:1,name:"Tarjeta de crédito",balance:2300,min:75,apr:28},{id:2,name:"Carro",balance:8500,min:200,apr:9},{id:3,name:"Teléfono",balance:700,min:50,apr:12},{id:4,name:"Renta atrasada",balance:1200,min:300,apr:0},{id:5,name:"Préstamo personal",balance:3000,min:150,apr:16}],expenses:[{id:1,name:"Comida",amount:32,cat:"Esencial"},{id:2,name:"Gasolina",amount:60,cat:"Esencial"},{id:3,name:"Restaurantes",amount:35,cat:"Hormiga"},{id:4,name:"Gaseosas / Snacks",amount:72,cat:"Hormiga"},{id:5,name:"Café",amount:46,cat:"Hormiga"},{id:6,name:"Uber / Transporte",amount:72,cat:"Variable"}]};
function cloneSeed(){return JSON.parse(JSON.stringify(seed))}
function safeGet(k){try{return localStorage.getItem(k)}catch(e){return null}}
function safeSet(k,v){try{localStorage.setItem(k,v)}catch(e){}}
let s;try{s=JSON.parse(safeGet(KEY)||"null")||cloneSeed()}catch(e){s=cloneSeed()}
let profile;try{profile=JSON.parse(safeGet(AUTH)||"null")}catch(e){profile=null}
let screen=profile?(s.onboarded?"home":"setupGoal"):"welcome",debtFilter="all",expenseFilter="all";
const $=q=>document.querySelector(q),esc=x=>String(x??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c])),money=n=>new Intl.NumberFormat(s.locale||undefined,{style:"currency",currency:s.currency,maximumFractionDigits:s.currency==="COP"?0:2}).format(+n||0);
function save(){safeSet(KEY,JSON.stringify(s));render()}function totals(){let debt=s.debts.reduce((a,x)=>a+x.balance,0),exp=s.expenses.reduce((a,x)=>a+x.amount,0),ants=s.expenses.filter(x=>x.cat==="Hormiga").reduce((a,x)=>a+x.amount,0),mins=s.debts.reduce((a,x)=>a+x.min,0);return{debt,exp,ants,mins,free:Math.max(0,s.income-exp)}}function flags(){return '<div class="languageDock"><button class="btn languageBtn" onclick="languageMenu()">🌐 '+localeName()+'⌄</button></div>'}
function localeName(){return {"es-US":"Español","es-CO":"Español · Colombia","es-ES":"Español · España","en-US":"English","pt-BR":"Português"}[s.locale]||"Español"}
function languageMenu(){modal('<h2>🌐 Idioma y región</h2><p class="muted">Arydebts adaptará palabras, formato y moneda a tu región.</p>'+[["es-CO","🇨🇴 Español · Colombia"],["es-ES","🇪🇸 Español · España"],["es-US","🌎 Español · Latinoamérica"],["en-US","🇺🇸 English"],["pt-BR","🇧🇷 Português"]].map(x=>'<button class="btn widebtn" onclick="setLocale(\''+x[0]+'\')">'+x[1]+'</button>').join("")+'<button class="btn widebtn" onclick="closeM()">Cerrar</button>')}
function setLocale(x){s.locale=x;closeM();save()}function dots(n){return '<div class="stepdots">'+[1,2,3,4,5].map(x=>'<i class="'+(x<=n?'on':'')+'"></i>').join("")+'</div>'}function logo(){return '<span class="aryLogo" aria-label="Arydebts"><i class="storm">☁</i><i class="sun">☀</i><i class="path">↗</i></span>'}
function head(title,sub=""){return '<div class="top"><div class="brandWrap">'+logo()+'<div class="brand"><b>ARY</b>DEBTS <span class="grad">Solution</span></div></div><button class="pill bell" onclick="go(\'notifications\')">🔔</button></div><div class="hello"><button class="btn tiny back" onclick="back()">‹ Volver</button><span class="muted">'+sub+'</span><h1>'+title+'</h1></div>'}
function welcome(){return '<section class="welcome blueprintWelcome"><div class="welcomeControls"><button class="languageClean" onclick="languageMenu()">🌐 <span>'+localeName().replace(" · Colombia","").replace(" · España","")+'</span>⌄</button><button class="themeClean" onclick="toggleTheme()">Modo oscuro <i class="'+(s.theme==="dark"?"on":"")+'"></i></button></div><div class="heroArtwork"><img src="assets/arydebts-hero.svg" alt="Camino desde el caos financiero hacia un futuro estable"></div><div class="welcomeBrand"><h1>Arydebts</h1><strong>Solution</strong><p>Tus deudas hoy, tu libertad mañana.</p></div><div class="featureStrip welcomeFeatures"><div><i>▤</i><b>Organiza</b><span>Tus finanzas en un solo lugar.</span></div><div><i>◷</i><b>Controla</b><span>Tus gastos y deudas fácilmente.</span></div><div><i>✓</i><b>Cumple</b><span>Alcanza tus metas y vive tranquilo.</span></div></div><button class="gradientAction heroStart" onclick="startChange()">Comenzar mi cambio <b>→</b></button><p class="accountPrompt">¿Ya tengo una cuenta? <button class="linkBtn" onclick="go(\'login\')">Iniciar sesión</button></p><div class="orLine"><span>o continúa con</span></div><div class="socialLaunch branded"><button class="apple" onclick="socialDemo(\'Apple\')"></button><button class="google" onclick="socialDemo(\'Google\')">G</button><button class="facebook" onclick="socialDemo(\'Facebook\')">f</button><button class="instagram" onclick="socialDemo(\'Instagram\')">◎</button><button class="discord" onclick="socialDemo(\'Discord\')">◉</button></div><div class="socialProof"><b>“Más de 100,000 personas ya están mejorando su vida”</b><span>👩🏽‍🦱　👨🏻　👩🏼　👨🏾</span></div><div class="trustStrip"><span>▣　Disponible en todos tus dispositivos</span><span>♢　Tus datos seguros<br><small>Privacidad garantizada</small></span></div></section>'}
function auth(mode){let up=mode==="signup";return '<section class="welcome auth"><button class="btn" onclick="go(\'welcome\')">‹ Volver</button><div class="logoMark grad">↗</div><h1>'+(up?'Este espacio es tuyo':'Qué bueno verte 👋')+'</h1><p class="muted">'+(up?'No tienes que tener tus finanzas perfectas para empezar. Solo cuéntanos dónde estás y avanzamos desde ahí.':'Vuelve a tu plan y continúa donde lo dejaste.')+'</p>'+(up?'<label>¿Cómo quieres que te llamemos?</label><input id="an" placeholder="Tu nombre">':'')+'<label>Correo electrónico</label><input id="ae" type="email" placeholder="tucorreo@ejemplo.com"><label>Contraseña</label><input id="ap" type="password" placeholder="••••••••"><button class="btn primary widebtn" onclick="localAuth(\''+mode+'\')">'+(up?'Crear mi espacio':'Entrar')+'</button><div class="socials"><button class="btn" onclick="socialDemo(\'Apple\')"> Apple</button><button class="btn" onclick="socialDemo(\'Google\')">G Google</button><button class="btn" onclick="socialDemo(\'Facebook\')">f Facebook</button></div><p class="muted">Estos accesos sociales son interfaz de demostración hasta conectar autenticación segura. No te pediremos contraseñas de esas plataformas aquí.</p></section>'}
function intro(){return '<section class="welcome">'+dots(1)+'<div class="heroLogo small">'+logo()+'</div><h1>Empieza a cambiar<br><span class="grad">tu vida.</span></h1><p>Vamos a convertir números que hoy pueden sentirse pesados en pasos pequeños y claros.</p><div class="notice"><b>Aquí puedes sentirte cómodo.</b><p>Si sigues un plan realista, Arydebts te ayudará a ordenar tus finanzas, reducir estrés y acercarte a esa casa, ese carro o esa tranquilidad que quieres construir.</p></div><button class="btn primary widebtn" onclick="go(\'setupIncome\')">Quiero empezar →</button></section>'}
function setupIncome(){return '<section class="blueprint onboarding">'+simpleTop("Tu ingreso")+'<div class="progressLine step2"><i></i></div><div class="stepLabel">Paso 2 de 5</div><h1>¿Cuánto dinero<br>recibes normalmente?</h1><p>Usaremos esto para construir un plan que sí puedas cumplir.</p><label>Ingreso</label><div class="moneyInput bigMoney"><span>'+s.currency+'</span><input id="oi" inputmode="decimal" value="'+s.income+'" placeholder="0"></div><label>¿Con qué frecuencia?</label><select id="of"><option value="weekly" '+(s.incomeFrequency==="weekly"?"selected":"")+'>Cada semana</option><option value="biweekly" '+(s.incomeFrequency==="biweekly"?"selected":"")+'>Cada quincena</option><option value="monthly" '+(s.incomeFrequency==="monthly"?"selected":"")+'>Cada mes</option></select><label>Moneda principal</label><select id="oc">'+currencies().map(c=>'<option '+(c===s.currency?"selected":"")+'>'+c+'</option>').join("")+'</select><button class="gradientAction" onclick="saveIncomeSetup()">Siguiente <b>→</b></button></section>'}
function setupGoal(){let goals=[["🏠","Comprar casa"],["🚗","Comprar carro"],["✈️","Viajar"],["🎓","Estudiar"],["💍","Casarme"],["👶","Familia"],["🪴","Libertad financiera"],["🌴","Negocio propio"],["💪","Pagar deudas"],["💡","Otra meta"]];return '<section class="blueprint goalsScreen"><div class="screenTop"><button class="bare backArrow" onclick="go(\'welcome\')">‹ <span>Volver</span></button><span class="avatarMini">👩🏻</span></div><div class="progressLine"><i></i></div><div class="stepLabel">Paso 1 de 5</div><h1>¿Cuáles son tus<br>metas actuales?</h1><p>Selecciona una o varias. Puedes agregar las tuyas.</p><div class="goalMatrix">'+goals.map(x=>'<button class="goalTile '+((s.goals||[]).includes(x[1])?'selected':'')+'" onclick="toggleGoal(\''+x[1]+'\')"><span>'+x[0]+'</span><b>'+x[1]+'</b></button>').join("")+'</div><button class="gradientAction" onclick="go(\'setupIncome\')">Siguiente <b>→</b></button></section>'}
function setupDebts(){return '<section class="blueprint onboarding">'+simpleTop("Tus deudas")+'<div class="progressLine step3"><i></i></div><div class="stepLabel">Paso 3 de 5</div><h1>Ahora pongamos tus<br>deudas sobre la mesa.</h1><p>Sin juicios. Tenerlas claras es empezar a controlarlas.</p><div class="debtList compactList">'+s.debts.map(debtBlueprint).join("")+'</div><button class="outlineAction" onclick="onboardingDebt()">＋ Agregar deuda</button><button class="gradientAction" onclick="go(\'setupExpenses\')">Siguiente <b>→</b></button></section>'}
function setupExpenses(){return '<section class="blueprint onboarding">'+simpleTop("Tus gastos")+'<div class="progressLine step4"><i></i></div><div class="stepLabel">Paso 4 de 5</div><h1>¿En qué se va<br>tu dinero?</h1><p>Agrega lo necesario, variable y esos pequeños gastos que se repiten.</p><div class="expenseList compactList">'+s.expenses.slice(0,7).map(expenseBlueprint).join("")+'</div><button class="outlineAction" onclick="expenseForm()">＋ Agregar gasto</button><button class="gradientAction" onclick="go(\'setupFinish\')">Siguiente <b>→</b></button></section>'}
function home(){let t=totals(),p=42;return '<section class="blueprint dashboard">'+appBar()+'<div class="commander"><span class="avatarLarge">👩🏻</span><div><h1>Buenos días<br>¡Comandante! 👋</h1><p>Hoy es un gran día para acercarte a tus metas.</p></div></div><section class="freedomCard"><b>Tu progreso hacia la libertad financiera</b><div class="freedomBody"><div class="ring"><b>'+p+'%</b></div><div class="debtNumbers"><span>Deuda total</span><strong>'+money(t.debt)+'</strong><span>Restante</span><strong>'+money(Math.max(0,t.debt*.58))+'</strong></div></div><div class="wave"></div></section><div class="metricGrid"><button onclick="go(\'income\')"><i>💰</i><span>Ingresos</span><b>'+money(s.income)+'</b></button><button onclick="go(\'expenses\')"><i>🎁</i><span>Gastos</span><b>'+money(t.exp)+'</b></button><button onclick="go(\'plan\')"><i>✚</i><span>Disponible</span><b>'+money(t.free)+'</b></button></div><div class="motivation">🌈 <b>Cada pequeña decisión<br>hace una gran diferencia.</b><button onclick="go(\'plan\')">→</button></div><div class="sectionTitle"><b>Tus próximos pagos</b><button onclick="go(\'calendar\')">Ver todos ›</button></div><div class="paymentList">'+s.debts.slice(0,3).map((d,i)=>paymentBlueprint(d,i)).join("")+'</div></section>'}
function row(i,n,sub,val,actions=""){return '<div class="row"><div class="rowleft"><span class="ico">'+i+'</span><div><strong>'+esc(n)+'</strong><span class="muted">'+esc(sub)+'</span></div></div><div><b>'+val+'</b>'+actions+'</div></div>'}function iconFor(n,c){let z=(n+" "+c).toLowerCase();return z.includes("tarjeta")?"💳":z.includes("carro")||z.includes("auto")?"🚗":z.includes("tel")||z.includes("móvil")||z.includes("cel")?"📱":z.includes("renta")||z.includes("alquiler")?"🏠":z.includes("prést")?"💰":z.includes("gasolina")?"⛽":z.includes("comida")||z.includes("restaurant")?"🍽️":z.includes("café")?"☕":z.includes("uber")||z.includes("transport")?"🚕":z.includes("gase")||z.includes("snack")?"🥤":"💸"}
function debts(){let list=s.debts.filter(d=>debtFilter==="paid"?d.balance<=0:debtFilter==="active"?d.balance>0:true);return '<section class="blueprint">'+appBar()+'<div class="titleRow"><h1>Mis deudas</h1><button class="roundPlus" onclick="debtForm()">＋</button></div><div class="segmented">'+[["all","Todas"],["active","Activas"],["paid","Pagadas"]].map(x=>'<button class="'+(debtFilter===x[0]?'on':'')+'" onclick="setDebtFilter(\''+x[0]+'\')">'+x[1]+'</button>').join("")+'</div><div class="debtList">'+list.map(debtBlueprint).join("")+'</div><button class="gradientAction" onclick="debtForm()">＋ Agregar deuda</button></section>'}
function income(){return head("Mis ingresos","Cada entrada de dinero puede tener una misión.")+'<section class="card full heroCard"><span class="muted">Ingreso principal</span><div class="kpi">'+money(s.income)+' <span class="mini">/ '+freqLabel()+'</span></div><button class="btn widebtn" onclick="incomeForm()">Editar ingreso</button></section><section class="card full notice"><b>💡 Tip de Arydebts</b><p>Si recibes ingresos extra, regístralos antes de gastarlos: así puedes decidir cuánto disfrutar y cuánto enviar a tu meta.</p></section>'}
function expenses(){let list=s.expenses.filter(e=>expenseFilter==="all"||e.cat===expenseFilter);return '<section class="blueprint">'+appBar()+'<div class="segmented expenseTabs">'+[["all","Todos"],["Esencial","Necesarios"],["Variable","Variables"],["Hormiga","Hormiga"]].map(x=>'<button class="'+(expenseFilter===x[0]?'on':'')+'" onclick="setExpenseFilter(\''+x[0]+'\')">'+x[1]+'</button>').join("")+'</div><div class="expenseList">'+list.map(expenseBlueprint).join("")+'</div><button class="gradientAction" onclick="expenseForm()">＋ Agregar gasto</button><button class="textAction" onclick="go(\'ants\')">Ver gastos hormiga →</button></section>'}
function ants(){let t=totals();return '<section class="blueprint">'+simpleTop("Gastos hormiga")+'<section class="pigCard"><div class="pig">🐷</div><div><small>Tus pequeños gastos sumaron</small><strong>'+money(t.ants)+'</strong><span>este mes</span><small>¡Esto equivale a '+money(t.ants/30)+' al día!</small></div></section><div class="antPresets">'+[1,2,5,10,20].map(v=>'<button onclick="quickAntPreset('+v+')">'+money(v)+'</button>').join("")+'</div><div class="quickAnt"><input id="quickAnt" inputmode="decimal" placeholder="Otro valor"><button class="gradientAction compact" onclick="addQuickAnt()">＋ Agregar rápido</button></div><div class="expenseList">'+s.expenses.filter(e=>e.cat==="Hormiga").map(expenseBlueprint).join("")+'</div><div class="savingTip">🛡️ <span>Si reduces estos gastos un 50%, podrías ahorrar <b>'+money(t.ants*.5)+'</b> al mes para tu deuda.</span></div><button class="gradientAction" onclick="go(\'expenses\')">Ver detalles</button></section>'}
function plan(){let t=totals(),essential=s.expenses.filter(e=>e.cat==="Esencial").reduce((a,e)=>a+e.amount,0),cut=t.ants/2,buffer=Math.min(50,s.income*.06),extra=Math.max(0,s.income-essential-(t.ants-cut)-t.mins-buffer),target=[...s.debts].sort((a,b)=>b.apr-a.apr)[0],items=[["🏠","Renta / Vivienda",Math.min(250,essential)],["🚗","Carro",Math.min(100,t.mins)],["🍽️","Comida",Math.min(100,essential)],["⛽","Gasolina",Math.min(60,essential)],["💳","Deuda #1",Math.min(150,t.mins)],["🟢","Fondo de emergencia",buffer],["💸","Gastos libres",Math.max(0,t.ants-cut)],["🎯","Ataque "+(target?.name||"deuda"),extra]];return '<section class="blueprint">'+appBar()+'<h1>Tu plan de esta semana</h1><p class="planIntro">Un plan humano para avanzar sin sentirte castigado.</p><section class="planHero"><small>Ingreso '+freqLabel()+'</small><strong>'+money(s.income)+'</strong><span>Distribución recomendada</span></section><div class="planRows">'+items.map((x,i)=>'<div class="planRow"><span>'+x[0]+' '+esc(x[1])+'</span><i><u class="bar'+(i%5)+'" style="width:'+Math.min(100,x[2]/Math.max(s.income,1)*100)+'%"></u></i><b>'+money(x[2])+'</b></div>').join("")+'</div><div class="savingTip">✨ <span><b>Tu siguiente mejor movimiento:</b><br>reduce a la mitad los gastos hormiga y dirige esa diferencia a '+esc(target?.name||"tu deuda prioritaria")+'.</span></div><button class="gradientAction" onclick="go(\'calendar\')">📅 Ver calendario completo</button></section>'}
function buy(){return head("¿Puedo comprar esto?","Antes de decirte sí o no, veamos qué significa para tu objetivo.")+'<section class="card full"><label>¿Qué quieres comprar?</label><input id="buyName" placeholder="Audífonos inalámbricos"><label>Precio</label><input id="buyPrice" type="number" placeholder="180"><button class="btn primary widebtn" onclick="checkBuy()">Analizar con cariño, pero con números</button><div id="buyResult"></div></section>'}
function assistant(){return '<section class="blueprint">'+appBar()+'<div class="assistantHero"><span class="botFace">🤖</span><div><h2>Asistente Arydebts</h2><b>En línea</b><small> • Siempre aquí para ayudarte</small></div></div><div class="chatThread"><div class="bubble">¡Hola! 👋 Soy tu asistente financiero. Puedes escribirme cualquier cosa, por ejemplo:</div>'+["¿Cómo puedo reducir mis gastos?","¿Puedo comprar esto?","Dame un plan para pagar mis deudas","¿Cuánto he ahorrado?"].map(q=>'<button class="promptChip" onclick="askPrompt(\''+q+'\')">'+q+' <b>›</b></button>').join("")+'<div id="chatlog"></div></div><div class="chatComposer"><input id="chatinput" placeholder="Escribe tu mensaje..."><button onclick="chat()">➤</button></div></section>'}
function calendar(){let now=new Date(),year=now.getFullYear(),month=now.getMonth(),label=new Intl.DateTimeFormat(s.locale||"es-US",{month:"long",year:"numeric"}).format(new Date(year,month,1)),count=new Date(year,month+1,0).getDate(),first=new Date(year,month,1).getDay(),payDays=s.debts.map((d,i)=>d.due?Math.min(count,Math.max(1,+String(d.due).slice(-2)||12+i*3)):Math.min(count,12+i*3)),cells=[...Array(first).fill(0),...Array.from({length:count},(_,i)=>i+1)];return '<section class="blueprint">'+simpleTop("Asistente de pagos")+'<div class="calendarCard"><div class="calendarMonth"><button>‹</button><b>'+label.toUpperCase()+'</b><button>›</button></div><div class="weekHead">'+["DOM","LUN","MAR","MIÉ","JUE","VIE","SÁB"].map(x=>"<span>"+x+"</span>").join("")+'</div><div class="calendarGrid blueprintCalendar">'+cells.map(d=>d?'<button class="day '+(payDays.includes(d)?"pay":"")+' '+(d===now.getDate()?"today":"")+'" onclick="showDay('+d+')">'+d+'</button>':'<i></i>').join("")+'</div><div id="dayDetail"></div></div><div class="sectionTitle"><b>Próximos pagos</b><button onclick="go(\'debts\')">Ver en lista</button></div><div class="paymentList">'+s.debts.slice(0,4).map((d,i)=>paymentBlueprint(d,Math.min(i,2))).join("")+'</div></section>'}
function progress(){let t=totals();return head("Tu progreso","Lo importante no es dónde empezaste, sino que ya estás avanzando.")+'<section class="card full"><div class="progressBox"><div class="ring"><b>42%</b></div><div><span class="muted">Deuda total</span><div class="kpi">'+money(t.debt)+'</div></div></div></section><section class="card full"><b>Historial de pagos</b><div class="list">'+[1250,1000,950].map((x,i)=>row("●",["Marzo","Febrero","Enero"][i],"Pago registrado",money(x))).join("")+'</div></section>'}
function goals(){let gs=s.goals||[s.goal];return head("Tus metas","Puedes tener varias y cambiarlas cuando cambie tu vida.")+'<section class="card full"><div>'+gs.map((g,i)=>'<span class="goalChip">🎯 '+esc(g)+' <button class="iconBtn" onclick="removeGoal('+i+')">×</button></span>').join("")+'</div><button class="btn primary widebtn" onclick="goalForm()">＋ Agregar meta</button></section><section class="card full savings"><span class="muted">Ahorro estimado siguiendo ajustes</span><div class="kpi">'+money(s.savings||0)+'</div><p class="muted">Aquí iremos acumulando los ahorros que registres al seguir tu plan.</p><button class="btn" onclick="addSaving()">Registrar ahorro</button></section>'}
function notifications(){return head("🔔 Notificaciones")+'<div class="list">'+[["🟠","Buen trabajo","Completaste una parte de tu plan."],["🔴","Un gasto merece atención","No pasa nada: revisémoslo antes de que afecte un pago importante."],["🟢","Pago próximo","Tienes una obligación acercándose."],["🔵","Nueva recomendación","Un pequeño ajuste puede acercarte a tu meta."]].map(x=>row(x[0],x[1],x[2],"")).join("")+'</div>'}
function profilePage(){return head("Mi perfil","Haz que Arydebts se sienta realmente tuyo.")+'<section class="card full"><div class="kpi">👤 '+esc(profile?.name||s.name)+'</div><span class="muted">'+esc(profile?.email||"Perfil local")+'</span><div class="menuGrid"><button class="btn menuItem" onclick="go(\'income\')">💵 Mis ingresos</button><button class="btn menuItem" onclick="go(\'debts\')">💳 Mis deudas</button><button class="btn menuItem" onclick="go(\'expenses\')">🧾 Mis gastos</button><button class="btn menuItem" onclick="go(\'goals\')">🎯 Metas</button><button class="btn menuItem" onclick="settings()">⚙️ Configuración</button><button class="btn menuItem" onclick="customizeHome()">🧩 Personalizar inicio</button><button class="btn menuItem" onclick="logout()">↩ Cerrar demo</button></div></section>'}
function customizeHome(){modal('<h2>🧩 Personalizar inicio</h2><p class="muted">Elige qué quieres ver primero. Esta versión guarda tus preferencias; el orden por arrastrar llegará con la base de datos.</p>'+[["home","🏠 Inicio"],["debts","💳 Deudas"],["expenses","🧾 Gastos"],["plan","🧭 Plan"],["more","••• Más"]].map((x,i)=>'<div class="row"><span>'+x[1]+'</span><div><button class="btn tiny" onclick="moveNav('+i+',-1)">↑</button><button class="btn tiny" onclick="moveNav('+i+',1)">↓</button></div></div>').join("")+'<button class="btn widebtn" onclick="closeM()">Listo</button>')}
function moveNav(i,d){let a=s.navOrder||["home","debts","expenses","plan","more"],j=i+d;if(j<0||j>=a.length)return;[a[i],a[j]]=[a[j],a[i]];s.navOrder=a;closeM();save();customizeHome()}
function more(){return '<section class="blueprint">'+simpleTop("Más")+'<div class="profileIdentity"><span class="avatarLarge">👨🏻</span><div><h2>'+esc(s.name||"Juan Cepeda")+'</h2><small>'+(profile?.email||"tu cuenta Arydebts")+'</small></div></div><div class="settingsList">'+[["♙","Mi perfil","profile"],["☑","Metas","goals"],["💰","Ahorros","progress"],["⇩","Exportar datos","progress"],["🔔","Notificaciones","notifications"],["◐","Modo oscuro","theme"],["🌐","Idioma","language"],["?","Ayuda y soporte","assistant"]].map(x=>'<button onclick="moreAction(\''+x[2]+'\')"><span>'+x[0]+'　'+x[1]+'</span><b>'+(x[2]==="theme"||x[2]==="language"?"":'›')+'</b></button>').join("")+'<button class="logoutRow" onclick="logout()">⇥　Cerrar sesión</button></div></section>'}
function render(){document.body.classList.toggle("lite",s.mode==="lite");document.documentElement.classList.toggle("theme-light",s.theme==="light");$("#app").innerHTML=(screens[screen]||home)();let hidden=["welcome","signup","login","intro","setupIncome","setupGoal","setupDebts","setupExpenses","setupFinish","debtEditor"];$("#nav").style.display=hidden.includes(screen)?"none":"grid";let navMap={home:["home","⌂","Inicio"],debts:["debts","▣","Deudas"],expenses:["expenses","◉","Gastos"],plan:["plan","▤","Plan"],more:["more","•••","Más"]};$("#nav").innerHTML=(s.navOrder||Object.keys(navMap)).map(k=>navMap[k]).map(x=>'<button class="'+(screen===x[0]?'active':'')+'" onclick="go(\''+x[0]+'\')"><b>'+x[1]+'</b>'+x[2]+'</button>').join("");let old=$(".modeToggle");if(old)old.remove();let b=document.createElement("button");b.className="btn modeToggle";b.textContent=s.mode==="lite"?"✨ Inmersivo":"◌ Lite";b.onclick=toggleMode;document.body.appendChild(b)}
function startChange(){if(!profile){profile={name:s.name||"Amigo",guest:true};safeSet(AUTH,JSON.stringify(profile))}go("setupGoal")}\nfunction go(x){history.pushState({screen:x},"","#"+x);screen=x;render();scrollTo(0,0)}
function back(){if(history.length>1)history.back();else go("home")}
window.addEventListener("popstate",e=>{screen=e.state?.screen||location.hash.slice(1)||screen;render()});
function quickAntPreset(v){$("#quickAnt").value=v;addQuickAnt()}
function addQuickAnt(){let v=parseNum($("#quickAnt").value);if(v<=0)return toast("Escribe un valor");s.expenses.push({id:Date.now(),name:"Gasto rápido",amount:v,cat:"Hormiga"});save();toast("Gasto hormiga agregado")}
function showDay(day){document.querySelectorAll(".day").forEach(x=>x.classList.remove("selected"));if(window.event?.currentTarget)window.event.currentTarget.classList.add("selected");let i=s.debts.findIndex((_,ix)=>Math.min(new Date(new Date().getFullYear(),new Date().getMonth()+1,0).getDate(),12+ix*3)===day),d=s.debts[i];$("#dayDetail").innerHTML=d?row(iconFor(d.name,"deuda"),d.name,"Vence el día "+day,money(d.min)):'<div class="notice">No tienes pagos registrados para este día.</div>'}
function dueRow(d,day,now){let diff=day-now.getDate(),cls=diff<=2?"dueSoon":diff<=14?"dueMid":"dueLater";return '<div class="row '+cls+'"><div class="rowleft"><span class="ico">'+iconFor(d.name,"deuda")+'</span><div><strong>'+esc(d.name)+'</strong><span class="muted">Día '+day+'</span></div></div><b>'+money(d.min)+'</b></div>'}
function goalForm(){modal('<h2>Nueva meta</h2><input id="newGoal" placeholder="Ej. Fondo para mi casa"><button class="btn primary widebtn" onclick="saveGoal()">Agregar</button>')}
function saveGoal(){let g=$("#newGoal").value.trim();if(!g)return;s.goals=[...(s.goals||[]),g];s.goal=s.goals[0]||g;closeM();save()}
function removeGoal(i){s.goals.splice(i,1);s.goal=s.goals[0]||"Mejorar mis finanzas";save()}
function addSaving(){modal('<h2>Registrar ahorro logrado</h2><input id="sv" type="text" inputmode="decimal" placeholder="Valor"><button class="btn primary widebtn" onclick="saveSaving()">Guardar</button>')}
function saveSaving(){s.savings=(s.savings||0)+parseNum($("#sv").value);closeM();save()}
document.addEventListener("keydown",e=>{if(e.key==="Enter"&&document.activeElement?.id==="chatinput"){e.preventDefault();chat()}})
function localAuth(mode){let e=$("#ae").value.trim(),p=$("#ap").value,n=mode==="signup"?$("#an").value.trim():(profile?.name||"Amigo");if(!e||!p||!n)return toast("Completa los campos");profile={name:n,email:e,localDemo:true};s.name=n;safeSet(AUTH,JSON.stringify(profile));safeSet(KEY,JSON.stringify(s));go(s.onboarded?"home":"setupGoal")}function socialDemo(x){toast(x+" se conectará con autenticación segura en la siguiente fase")}function logout(){try{localStorage.removeItem(AUTH)}catch(e){}profile=null;go("welcome")}function toggleMode(){s.mode=s.mode==="lite"?"immersive":"lite";save()}function toggleTheme(){s.theme=s.theme==="light"?"dark":"light";save()}function setDebtFilter(x){debtFilter=x;render()}function setExpenseFilter(x){expenseFilter=x;render()}
function saveIncomeSetup(){s.income=parseNum($("#oi").value);s.incomeFrequency=$("#of").value;s.currency=$("#oc").value;safeSet(KEY,JSON.stringify(s));go("setupDebts")}function toggleGoal(x){s.goals=s.goals||[];s.goals=s.goals.includes(x)?s.goals.filter(g=>g!==x):[...s.goals,x];s.goal=s.goals[0]||"Mejorar mis finanzas";save()}function chooseGoal(x){s.goal=x;s.goals=s.goals||[];if(!s.goals.includes(x))s.goals.push(x);save();go("setupDebts")}function finishOnboarding(){s.onboarded=true;save();go("home")}function freqLabel(){return {weekly:"semanal",biweekly:"quincenal",monthly:"mensual"}[s.incomeFrequency]||"semanal"}function currencies(){return ["USD","COP","MXN","EUR","BRL","GBP","CAD","ARS","CLP","PEN","JPY","CHF","AUD","NZD","INR","CNY","KRW","SGD","HKD","SEK","NOK","DKK","PLN","CZK","HUF","RON","TRY","ZAR","AED","SAR","ILS","THB","PHP","IDR","MYR","VND"]}
function modal(h){$("#modal").innerHTML='<div class="sheet">'+h+'</div>';$("#modal").classList.remove("hidden")}function closeM(){$("#modal").classList.add("hidden")}function toast(x){let t=$("#toast");t.textContent=x;t.classList.add("show");setTimeout(()=>t.classList.remove("show"),2200)}
function debtForm(id=null){window._editingDebt=id;let d=s.debts.find(x=>x.id===id)||{};window._debtIcon=d.icon||iconFor(d.name||"","deuda");go("debtEditor")}
function debtEditor(){let id=window._editingDebt,d=s.debts.find(x=>x.id===id)||{};return '<section class="blueprint debtEditor">'+simpleTop(id?"Editar deuda":"Agregar deuda")+'<label>Moneda</label><button class="selectLike" onclick="settings()"><span>🇺🇸　'+s.currency+'</span><b>⌄</b></button><small class="fxNote">Tipo de cambio real se conectará con infraestructura segura.</small><label>Icono</label><div class="iconPicker">'+["💳","🚗","🏠","📱","🎓","✈️","🛒","❤️","👗","🪙"].map(x=>'<button class="'+(window._debtIcon===x?"selected":"")+'" onclick="pickDebtIcon(\''+x+'\')">'+x+'</button>').join("")+'</div><label>Nombre de la deuda</label><input id="n" value="'+esc(d.name||"")+'" placeholder="Ej. Tarjeta de crédito"><label>Valor total</label><div class="moneyInput"><span>'+s.currency+'</span><input id="b" inputmode="decimal" value="'+(d.balance??"")+'" placeholder="0"></div><div class="amountPresets">'+[50,100,250,500].map(x=>'<button onclick="presetAmount('+x+')">+'+money(x)+'</button>').join("")+'</div><label>Pago mínimo</label><div class="moneyInput"><span>'+s.currency+'</span><input id="m" inputmode="decimal" value="'+(d.min??"")+'"></div><label>Fecha de vencimiento</label><input id="due" type="date" value="'+(d.due||"")+'"><label>Notas (opcional)</label><textarea id="note" placeholder="Ej. Últimos 4 dígitos, banco...">'+esc(d.note||"")+'</textarea><label>APR / interés %</label><input id="a" inputmode="decimal" value="'+(d.apr??"")+'"><div class="editorActions"><button onclick="cancelDebtEditor()">Cancelar</button><button class="gradientAction" onclick="saveDebt('+(id||"null")+')">Guardar deuda</button></div>'+(id?'<button class="deleteFull" onclick="deleteDebtAndBack('+id+')">Eliminar deuda</button>':'')+'</section>'}
function saveDebt(id){let n=$("#n").value.trim(),b=parseNum($("#b").value),m=parseNum($("#m").value),a=parseNum($("#a").value);if(!n||b<0)return toast("Escribe un nombre y saldo válido");let obj={name:n,balance:b,min:m,apr:a,due:$("#due")?.value||"",note:$("#note")?.value||"",icon:window._debtIcon||"💳"};if(id)Object.assign(s.debts.find(x=>x.id===id),obj);else s.debts.push({id:Date.now(),...obj});safeSet(KEY,JSON.stringify(s));window._editingDebt=null;let dest=window._returnAfterDebt||"debts";window._returnAfterDebt=null;go(dest)}
function pickDebtIcon(x){window._debtIcon=x;render()}
function editDebt(id){debtForm(id)}
function cancelDebtEditor(){window._editingDebt=null;let dest=window._returnAfterDebt||"debts";window._returnAfterDebt=null;go(dest)}
function deleteDebt(id){s.debts=s.debts.filter(x=>x.id!==id);save()}
function deleteDebtAndBack(id){s.debts=s.debts.filter(x=>x.id!==id);safeSet(KEY,JSON.stringify(s));window._editingDebt=null;go("debts")}
function presetAmount(x){let el=$("#b");el.value=(parseNum(el.value)+x).toString()}
function parseNum(v){return Number(String(v).replace(/[^0-9.,-]/g,"").replace(",", "."))||0}
function expenseForm(id=null){let e=s.expenses.find(x=>x.id===id)||{};modal('<h2>'+(id?"Editar gasto":"Nuevo gasto")+'</h2><label>Nombre</label><input id="n" value="'+esc(e.name||"")+'" placeholder="Comida, gasolina, café..."><label>Monto</label><input id="b" type="text" inputmode="decimal" value="'+(e.amount??"")+'"><div class="amountPresets">'+[5,10,25,50].map(x=>'<button class="btn tiny" onclick="presetExpense('+x+')">+'+money(x)+'</button>').join("")+'</div><label>Categoría</label><select id="c"><option>Esencial</option><option>Hormiga</option><option>Variable</option></select><button class="btn primary widebtn" onclick="saveExpense('+(id||"null")+')">Guardar</button><button class="btn widebtn" onclick="closeM()">Cancelar</button>')}function saveExpense(id){let n=$("#n").value.trim(),b=parseNum($("#b").value),c=$("#c").value;if(!n||b<0)return toast("Completa nombre y monto");if(id){let e=s.expenses.find(x=>x.id===id);Object.assign(e,{name:n,amount:b,cat:c})}else s.expenses.push({id:Date.now(),name:n,amount:b,cat:c});closeM();save()}function editExpense(id){expenseForm(id)}function deleteExpense(id){s.expenses=s.expenses.filter(x=>x.id!==id);save()}function presetExpense(x){let el=$("#b");el.value=(parseNum(el.value)+x).toString()}
function incomeForm(){modal('<h2>Ingreso</h2><input id="inc" type="number" value="'+s.income+'"><select id="if"><option value="weekly">Semanal</option><option value="biweekly">Quincenal</option><option value="monthly">Mensual</option></select><button class="btn primary widebtn" onclick="setIncome()">Guardar</button>')}function setIncome(){s.income=+$("#inc").value||0;s.incomeFrequency=$("#if").value;closeM();save()}
function settings(){modal('<h2>Configuración</h2><div class="settingsGroup"><label>Saludo personalizado</label><input id="greet" value="'+esc(s.greeting||"Hola")+'" placeholder="Buenos días, comandante"><label>Idioma / región</label><select id="loc"><option value="es-US">Español (Latinoamérica)</option><option value="es-CO">Español (Colombia)</option><option value="es-ES">Español (España)</option><option value="en-US">English (US)</option><option value="pt-BR">Português (Brasil)</option></select><label>Moneda base</label><select id="cur">'+currencies().map(c=>'<option '+(c===s.currency?"selected":"")+'>'+c+'</option>').join("")+'</select></div><div class="settingsGroup"><label>Apariencia</label><select id="theme"><option value="dark">Oscuro</option><option value="light">Claro</option></select><select id="motion"><option value="immersive">Inmersivo</option><option value="lite">Lite</option></select></div><p class="muted">Conversión FX real: pendiente de conectar a una fuente de tasas. No alteraremos tus números con tasas inventadas.</p><button class="btn primary widebtn" onclick="setSettings()">Guardar</button><button class="btn widebtn" onclick="closeM()">Cerrar</button>')}function setSettings(){s.greeting=$("#greet").value.trim()||"Hola";s.locale=$("#loc").value;s.currency=$("#cur").value;s.theme=$("#theme").value;s.mode=$("#motion").value;closeM();save()}
function checkBuy(){let p=+$("#buyPrice").value,n=$("#buyName").value||"Esta compra",t=totals(),ok=p<=t.free*.25;$("#buyResult").innerHTML='<div class="notice" style="margin-top:12px"><b>'+(ok?"💙 Puedes considerarlo.":"🫶 Yo esperaría un poco.")+'</b><p>'+esc(n)+' cuesta '+money(p)+'. '+(ok?"Cabe dentro de una parte razonable de tu disponible, pero revisa tus próximos pagos antes de decidir.":"No es un regaño: hoy usaría demasiado de tu disponible y puede quitarle tranquilidad a un pago importante.")+'</p></div>'}
function chat(){let i=$("#chatinput"),v=i.value.trim();if(!v)return;$("#chatlog").innerHTML+='<div class="bubble me">'+esc(v)+'</div><div class="bubble">Te escucho. No tienes que arreglar todo hoy. En esta demo puedo ayudarte a volver a tres prioridades: proteger lo esencial, cubrir obligaciones próximas y elegir un gasto controlable para reducir. La IA conversacional real se conectará de forma segura después.</div>';i.value=""}
render()
function appBar(){return '<div class="appBar"><button class="bare" onclick="go(\'notifications\')">♧</button><div class="wordmark">Arydebts<small>Solution</small></div><span class="avatarMini">👩🏻</span></div>'}
function simpleTop(title){return '<div class="screenTop"><button class="bare backArrow" onclick="back()">‹</button><h2>'+title+'</h2><span class="avatarMini">👩🏻</span></div>'}
function paymentBlueprint(d,i){return '<button class="paymentItem" onclick="go(\'calendar\')"><span class="debtIcon">'+iconFor(d.name,"deuda")+'</span><span><b>'+esc(d.name)+'</b><small>'+(d.due||["12 de abr. 2025","20 de abr. 2025","28 de abr. 2025"][i]||"Próximo")+'</small></span><span class="paymentRight"><b>'+money(d.min)+'</b><em class="urgency u'+i+'">'+(["En 2 días","En 1 semana","En 3 semanas"][i]||"Próximo")+'</em></span></button>'}
function debtBlueprint(d){let pct=Math.max(8,Math.min(92,100-(d.balance/Math.max(d.balance+d.min*8,1))*100));return '<button class="debtItem" onclick="editDebt('+d.id+')"><span class="debtIcon">'+iconFor(d.name,"deuda")+'</span><span class="debtCopy"><b>'+esc(d.name)+'</b><small>Pago mínimo: '+money(d.min)+'</small><small>Vence: '+esc(d.due||"Próximamente")+'</small></span><span class="debtAmount"><b>'+money(d.balance)+'</b><i><u style="width:'+pct+'%"></u></i></span></button>'}
function expenseBlueprint(e){return '<button class="expenseItem" onclick="editExpense('+e.id+')"><span class="debtIcon">'+iconFor(e.name,e.cat)+'</span><span><b>'+esc(e.name)+'</b><small>'+(e.cat==="Hormiga"?"Ayer":"Hoy")+'</small></span><strong>'+money(e.amount)+'</strong></button>'}
function askPrompt(q){let i=$("#chatinput");if(i){i.value=q;chat()}}
function moreAction(x){if(x==="theme")return toggleTheme();if(x==="language")return languageMenu();go(x)}

const screens={welcome,signup:()=>auth("signup"),login:()=>auth("login"),intro,setupIncome,setupGoal,setupDebts,setupExpenses,setupFinish,home,debts,debtEditor,income,expenses,ants,plan,buy,assistant,calendar,progress,goals,notifications,profile:profilePage,more};

function setupFinish(){let t=totals();return '<section class="blueprint onboarding finishSetup">'+simpleTop("Tu punto de partida")+'<div class="progressLine step5"><i></i></div><div class="stepLabel">Paso 5 de 5</div><div class="finishOrb">✓</div><h1>Ya tenemos lo necesario.</h1><p>Arydebts organizará tus próximos pasos con la información que acabas de registrar.</p><div class="summaryGrid"><div><span>Ingreso</span><b>'+money(s.income)+'</b></div><div><span>Deuda</span><b>'+money(t.debt)+'</b></div><div><span>Gastos</span><b>'+money(t.exp)+'</b></div><div><span>Disponible</span><b>'+money(t.free)+'</b></div></div><button class="gradientAction" onclick="finishOnboarding()">Crear mi plan ✦</button></section>'}
function onboardingDebt(){window._editingDebt=null;window._returnAfterDebt="setupDebts";go("debtEditor")}
;