(function(){
'use strict';
const model=window.aryExperience94,quoteKey='ary-visit-quote-v94';
const lang=()=>s.locale==='en-US'?'en':s.locale==='pt-BR'?'pt':'es';
const words={
 es:{back:'Volver',more:'Más',analysis:'Análisis',analysisHint:'Entiende tus ingresos, tus gastos y tu patrimonio.',tools:'Tus herramientas',calendar:'Calendario',goals:'Mis metas',progress:'Mi progreso',buy:'¿Puedo comprar esto?',assistant:'Asistente Arydebts',account:'Tu cuenta y preferencias',profile:'Mi perfil',appearance:'Accesibilidad y estilo',preferences:'Preferencias de la app',notifications:'Notificaciones',community:'Novedades y comunidad',announcements:'Centro de anuncios',events:'Eventos y celebraciones',support:'Apoyar el proyecto',feedback:'Comentarios',logout:'Cerrar sesión',guide:'Conoce Arydebts',guideHint:'Explora la app con Ary',gotIt:'Entendido',stop:'Terminar guía',aria:'Consejo de Ary',hello:'Soy Ary. Este es tu punto de partida.',
 quotes:['Un paso pequeño también te acerca a tu meta.','Entender tus números es empezar a tomar el control.','Hoy puedes elegir una decisión que cuide tu futuro.','Tu progreso se construye con lo que haces cada día.','Dale un propósito a tu próximo paso.','Cada gasto que registras te ayuda a ver con claridad.','Avanza a tu ritmo. La constancia también cuenta.','Tu tranquilidad merece un espacio en tu plan.','No necesitas hacerlo todo hoy: empieza por una cosa.','Revisar tu plan es cuidar lo que estás construyendo.','Reconoce tus avances, incluso los más pequeños.','Tu próxima buena decisión puede empezar aquí.'],
 tips:{home:['Soy Ary. Este es tu punto de partida.','Ya registraste tu información. Revisa el disponible estimado y entra a Tu plan para elegir tu próximo paso.','Ver mi plan','plan'],expenses:['Tus gastos, con claridad.','Registra cada gasto con su fecha. Aquí puedes editarlo, organizarlo por categoría y distinguir los gastos previstos de los que ya pagaste.','Agregar un gasto','expense'],debts:['Cada pago cuenta.','Revisa tus saldos y registra los pagos que realmente hiciste. Así se actualiza cuánto debes y puedes seguir tu avance.','Ver mi plan','plan'],plan:['Elige tu próximo paso.','Aquí verás el margen estimado, los pagos pendientes y una prioridad sugerida. Revisa las fechas en Calendario antes de organizar tu semana.','Ver calendario','calendar'],analysis:['Entiende cómo cambia tu dinero.','Compara períodos y categorías. Registra cobros reales y bienes; guarda tu patrimonio de hoy para comenzar su evolución.','Explorar mis gastos','expenses'],ants:['Los pequeños gastos también cuentan.','Revisa los gastos hormiga y elige un cambio que puedas sostener. Las sugerencias son una guía, no un ahorro que ya lograste.','Ver mis gastos','expenses'],income:['Tu ingreso orienta el presupuesto.','Actualiza cuánto recibes normalmente y con qué frecuencia. Los cobros reales se registran por separado en Análisis.','Ver análisis','analysis'],calendar:['Tu semana, a la vista.','Toca un día para revisar tus vencimientos y recordatorios. Agrega fechas reales y registra un pago solo cuando lo hayas realizado.','Ver mis deudas','debts'],goals:['Dale dirección a tu esfuerzo.','Elige tu meta principal y registra el ahorro que vayas logrando. Puedes cambiar tus metas cuando lo necesites.','Ver mi plan','plan'],more:['Tus herramientas están aquí.','Análisis aparece primero. Abre las herramientas que necesites y despliega las preferencias o novedades cuando quieras.','Abrir análisis','analysis']}},
 en:{back:'Back',more:'More',analysis:'Analysis',analysisHint:'Understand your income, spending and net worth.',tools:'Your tools',calendar:'Calendar',goals:'My goals',progress:'My progress',buy:'Can I buy this?',assistant:'Arydebts assistant',account:'Your account and preferences',profile:'My profile',appearance:'Accessibility and style',preferences:'App preferences',notifications:'Notifications',community:'Updates and community',announcements:'Announcement center',events:'Events and celebrations',support:'Support the project',feedback:'Feedback',logout:'Sign out',guide:'Discover Arydebts',guideHint:'Explore the app with Ary',gotIt:'Got it',stop:'End guide',aria:'Tip from Ary',
 quotes:['A small step still moves you toward your goal.','Understanding your numbers is a first step toward control.','Choose one decision today that cares for your future.','Progress grows through your everyday choices.','Give your next step a purpose.','Every expense you record helps you see more clearly.','Move at your own pace. Consistency matters too.','Your peace of mind deserves a place in your plan.','You do not need to do everything today: start with one thing.','Reviewing your plan protects what you are building.','Recognize your progress, even the smallest steps.','Your next good decision can begin here.'],
 tips:{home:["I'm Ary. This is your starting point.",'Your information is ready. Review your estimated available amount and open Your plan to choose your next step.','View my plan','plan'],expenses:['See your spending clearly.','Record each expense with its date. Edit it, organize it by category and distinguish planned expenses from those already paid.','Add an expense','expense'],debts:['Every payment matters.','Review balances and record payments you actually made. This updates how much you owe and helps track your progress.','View my plan','plan'],plan:['Choose your next step.','See estimated margin, pending payments and a suggested priority. Review dates in Calendar before organizing your week.','View calendar','calendar'],analysis:['Understand how your money changes.','Compare periods and categories. Record actual receipts and assets; save today’s net worth to begin its history.','Explore my expenses','expenses'],ants:['Small expenses matter too.','Review small expenses and choose a sustainable change. Suggestions are guidance, not savings already achieved.','View my expenses','expenses'],income:['Income guides your budget.','Update what you normally receive and how often. Actual receipts are recorded separately in Analysis.','View analysis','analysis'],calendar:['See your week at a glance.','Select a day to review deadlines and reminders. Add actual dates and record a payment only after making it.','View my debts','debts'],goals:['Give your effort direction.','Choose your main goal and record savings you achieve. Change your goals whenever you need.','View my plan','plan'],more:['Your tools are here.','Analysis comes first. Open the tools you need and expand preferences or updates when you want.','Open analysis','analysis']}},
 pt:{back:'Voltar',more:'Mais',analysis:'Análise',analysisHint:'Entenda sua renda, seus gastos e seu patrimônio.',tools:'Suas ferramentas',calendar:'Calendário',goals:'Minhas metas',progress:'Meu progresso',buy:'Posso comprar isso?',assistant:'Assistente Arydebts',account:'Sua conta e preferências',profile:'Meu perfil',appearance:'Acessibilidade e estilo',preferences:'Preferências do app',notifications:'Notificações',community:'Novidades e comunidade',announcements:'Central de novidades',events:'Eventos e celebrações',support:'Apoiar o projeto',feedback:'Comentários',logout:'Sair',guide:'Conheça o Arydebts',guideHint:'Explore o app com Ary',gotIt:'Entendi',stop:'Encerrar guia',aria:'Dica de Ary',
 quotes:['Um pequeno passo também aproxima você da sua meta.','Entender seus números é começar a assumir o controle.','Escolha hoje uma decisão que cuide do seu futuro.','Seu progresso cresce com suas escolhas de cada dia.','Dê um propósito ao seu próximo passo.','Cada gasto registrado ajuda você a enxergar com clareza.','Avance no seu ritmo. A constância também conta.','Sua tranquilidade merece um lugar no seu plano.','Não precisa fazer tudo hoje: comece por uma coisa.','Revisar seu plano protege o que você está construindo.','Reconheça seus avanços, mesmo os menores.','Sua próxima boa decisão pode começar aqui.'],
 tips:{home:['Sou Ary. Este é seu ponto de partida.','Seus dados estão prontos. Veja o disponível estimado e abra Seu plano para escolher o próximo passo.','Ver meu plano','plan'],expenses:['Seus gastos, com clareza.','Registre cada gasto com sua data. Edite, organize por categoria e diferencie gastos previstos daqueles já pagos.','Adicionar gasto','expense'],debts:['Cada pagamento conta.','Confira os saldos e registre os pagamentos realmente feitos. Assim o saldo devido é atualizado e você acompanha seu progresso.','Ver meu plano','plan'],plan:['Escolha seu próximo passo.','Veja a margem estimada, pagamentos pendentes e uma prioridade sugerida. Confira as datas no Calendário antes de organizar a semana.','Ver calendário','calendar'],analysis:['Entenda como seu dinheiro muda.','Compare períodos e categorias. Registre recebimentos reais e bens; salve o patrimônio de hoje para iniciar o histórico.','Explorar meus gastos','expenses'],ants:['Pequenos gastos também contam.','Revise os pequenos gastos e escolha uma mudança sustentável. Sugestões são orientações, não economias já alcançadas.','Ver meus gastos','expenses'],income:['A renda orienta o orçamento.','Atualize quanto normalmente recebe e com que frequência. Os recebimentos reais ficam separados em Análise.','Ver análise','analysis'],calendar:['Sua semana, à vista.','Escolha um dia para ver vencimentos e lembretes. Adicione datas reais e registre um pagamento apenas depois de realizá-lo.','Ver minhas dívidas','debts'],goals:['Dê direção ao seu esforço.','Escolha sua meta principal e registre a economia alcançada. Você pode mudar suas metas quando precisar.','Ver meu plano','plan'],more:['Suas ferramentas estão aqui.','Análise aparece primeiro. Abra as ferramentas necessárias e expanda preferências ou novidades quando quiser.','Abrir análise','analysis']}}
};
const tx=()=>words[lang()];
let quoteIndex=0;
function rotate(){let previous=-1;try{previous=JSON.parse(localStorage.getItem(quoteKey)||'-1')}catch{}quoteIndex=model.nextQuote(previous,12);safeSet(quoteKey,JSON.stringify(quoteIndex))}
rotate();
window.aryVisitQuote94=()=>tx().quotes[quoteIndex];
const robot=`<svg viewBox="0 0 100 110" aria-hidden="true" focusable="false"><defs><linearGradient id="aryMetal94" x2="1" y2="1"><stop stop-color="#effaff"/><stop offset="1" stop-color="#b8c9e9"/></linearGradient></defs><ellipse cx="50" cy="102" rx="27" ry="5" fill="#7163a4" opacity=".16"/><path d="M50 12V5" stroke="#8b7cd5" stroke-width="3"/><circle cx="50" cy="5" r="4" fill="#54d6c7"/><rect x="21" y="15" width="58" height="46" rx="19" fill="url(#aryMetal94)"/><rect x="15" y="31" width="7" height="17" rx="3" fill="#9d8ad7"/><rect x="78" y="31" width="7" height="17" rx="3" fill="#9d8ad7"/><rect x="27" y="25" width="46" height="28" rx="12" fill="#15263e"/><g class="aryEyes94" fill="#72eddd"><rect x="36" y="32" width="6" height="8" rx="3"/><rect x="58" y="32" width="6" height="8" rx="3"/></g><path class="aryMouth94" d="M44 44q6 5 12 0" fill="none" stroke="#72eddd" stroke-width="2" stroke-linecap="round"/><path d="M32 70q18-12 36 0v19q-18 13-36 0z" fill="url(#aryMetal94)"/><circle cx="50" cy="78" r="6" fill="#8772d5"/><path d="m47 78 2 2 4-5" stroke="white" fill="none" stroke-width="2"/><path d="M30 72 20 85" stroke="#b8c9e9" stroke-width="7" stroke-linecap="round"/><g class="aryHand94"><path d="m70 72 13-9 5-15" stroke="#b8c9e9" stroke-width="7" stroke-linecap="round"/><circle cx="88" cy="46" r="5" fill="#effaff"/></g><path d="M40 94v5m20-5v5" stroke="#9d8ad7" stroke-width="8" stroke-linecap="round"/></svg>`;
const motif={expenses:'<path d="M22 10q0-5 4-6" fill="none" stroke="#87c49b" stroke-width="2"/><ellipse cx="22" cy="24" rx="15" ry="14" fill="#ffac65"/><path d="m12 22 6-4v7zm14-4 6 4-6 3zM13 29q9 9 18 0" fill="#392345"/>',debts:'<path d="M28 5a17 17 0 1 0 9 28A16 16 0 0 1 28 5" fill="#dec38d"/><path d="m10 7 2 4 4 2-4 2-2 4-2-4-4-2 4-2z" fill="#c09cdf"/>',plan:'<path d="m22 18 3-6 3 6q8-10 15-5-6 4-5 12-7-3-10 4-6 5-12 0-3-7-10-4 1-8-5-12 7-5 15 5z" fill="#b99ae3"/>',more:'<path d="m23 6 11 27H12z" fill="#b79bdc"/><path d="M5 34q17-9 35 0" fill="none" stroke="#b79bdc" stroke-width="5" stroke-linecap="round"/><path d="m16 25 14-2 2 6-15 2z" fill="#e8ae72"/>',analysis:'<path d="m22 6 3 11 12 5-12 4-3 12-4-12-11-4 11-5z" fill="#e8c582"/><circle cx="36" cy="9" r="2" fill="#b69cdf"/>'};
const beforeHead=window.head;
window.head=(title,sub='')=>{let html=beforeHead(title,sub),back=html.match(/<button\b[^>]*class="[^"]*\bback\b[^"]*"[^>]*>[\s\S]*?<\/button>/)?.[0];if(back){html=html.replace(back,'');back=back.replace('‹ Volver','‹ '+tx().back);html=html.replace('<div class="hello',`<div class="sectionTools94">${back}</div><div class="hello`)}html=html.replace('class="hello','class="hello sectionHeader94');html=html.replace(/(<span class="muted">[\s\S]*?<\/span>)(<h1>[\s\S]*?<\/h1>)/,'$2$1');if(screen!=='home'&&window.aryBackdropSeason71?.()==='halloween'){const svg=`<span class="sectionDetail94" aria-hidden="true"><svg viewBox="0 0 44 44" focusable="false">${motif[screen]||motif.analysis}</svg></span>`;html=html.replace('</h1>',`</h1>${svg}`)}return html};
const link=(route,icon,label)=>`<button type="button" class="btn moreLink94" onclick="go('${route}')"><span aria-hidden="true">${icon}</span><span>${label}</span><span aria-hidden="true">›</span></button>`;
screens.more=()=>{const x=tx();return head(x.more)+`<div class="more94" data-ary-copy><button type="button" class="card analysisFirst94" onclick="go('analysis')"><span class="analysisIcon94" aria-hidden="true">▥</span><span><b>${x.analysis}</b><small>${x.analysisHint}</small></span><span aria-hidden="true">↗</span></button><section class="moreSection94"><h2>${x.tools}</h2><div class="moreGrid94">${[['calendar','◷',x.calendar],['goals','◎',x.goals],['progress','↗',x.progress],['buy','🛍',x.buy],['assistant','✦',x.assistant]].map(a=>link(...a)).join('')}</div></section><button type="button" class="btn guideLaunch94" onclick="aryStartGuide94()"><span class="guideLaunchIcon94" aria-hidden="true">✦</span><span><b>${x.guide}</b><small>${x.guideHint}</small></span><span aria-hidden="true">›</span></button><details class="moreDetails94"><summary>${x.account}</summary><div class="moreGrid94">${link('profile','◉',x.profile)+link('appearance','◐',x.appearance)+link('notifications','♧',x.notifications)}<button class="btn moreLink94" onclick="aryV18Settings()">⚙ ${x.preferences}</button><button class="btn moreLink94 logout58" onclick="logout()">${x.logout}</button></div></details><details class="moreDetails94"><summary>${x.community}</summary><div class="moreGrid94">${[['announcements','✧',x.announcements],['events','◉',x.events],['support','♡',x.support],['feedback','☏',x.feedback]].map(a=>link(...a)).join('')}</div></details></div>`};
let visibleRoute=null,lastRoute=null;
const persistGuide=state=>{s.guide94=state;safeSet(KEY,JSON.stringify(s))};
function guideMarkup(route){const x=tx(),[title,description,action,target]=x.tips[route];return `<aside class="aryGuide94" aria-label="${x.aria}" data-ary-copy><div class="aryRobot94">${robot}<small>ARY</small></div><div class="aryGuideCopy94"><b>${title}</b><p>${description}</p><div class="aryGuideActions94"><button type="button" class="btn tiny guidePrimary94" onclick="aryGuideAction94('${target}')">${action}</button><button type="button" class="btn tiny" onclick="aryDismissGuide94()">${x.gotIt}</button></div><button type="button" class="guideStop94" onclick="aryEndGuide94()">${x.stop}</button></div></aside>`}
function paintQuote(){if(!model.routes.includes(screen)||screen==='home')return;const subtitle=document.querySelector('#app .sectionHeader94>.muted');if(subtitle){subtitle.hidden=false;subtitle.textContent=aryVisitQuote94()}}
function enhance(){paintQuote();const header=document.querySelector('#app .sectionHeader94');if(!header)return;header.dataset.section94=screen;header.dataset.season94=window.aryBackdropSeason71?.()||'everyday';if(lastRoute!==screen){visibleRoute=null;lastRoute=screen}if(!profile||!s.onboarded||s.guide94?.active!==true||!model.routes.includes(screen))return;if(visibleRoute!==screen){const next=model.present(s.guide94,screen);if(!next.show)return;visibleRoute=screen;persistGuide(next.state)}if(!document.querySelector('.aryGuide94'))header.insertAdjacentHTML('afterend',guideMarkup(screen))}
const renderBefore=window.render;window.render=()=>{const result=renderBefore();enhance();return result};
window.aryDismissGuide94=()=>{visibleRoute=null;persistGuide(model.dismiss(s.guide94));render();document.querySelector('#app h1')?.focus?.()};
window.aryEndGuide94=()=>{visibleRoute=null;persistGuide(model.end(s.guide94));render()};
window.aryStartGuide94=()=>{visibleRoute=null;lastRoute=null;persistGuide(model.begin());go('home')};
window.aryGuideAction94=target=>{aryDismissGuide94();if(target==='expense')expenseForm();else if(model.routes.includes(target))go(target)};
const finishBefore=window.aryFinishOnboarding54;
window.aryFinishOnboarding54=function(){if(!s.onboarded){s.guide94=model.begin();visibleRoute=null;lastRoute=null}return finishBefore.apply(this,arguments)};window.finishOnboarding=window.aryFinishOnboarding54;
for(const name of ['aryNextQuote72','aryFavoriteQuote72']){const before=window[name];if(before)window[name]=function(){const result=before.apply(this,arguments);paintQuote();return result}}
let away=false;
document.addEventListener('visibilitychange',()=>{if(document.hidden){away=true;return}if(away){away=false;rotate();paintQuote()}});
render();
})();
