(()=>{
  const L={
    'es-US':{title:'Preferencias de la app',desc:'Opciones generales de Arydebts. Tu información personal vive en Mi perfil.',language:'Idioma y región',languaged:'Elige el idioma y formato que quieres usar.',change:'🌐 Cambiar idioma',close:'Cerrar',settings:'⚙️ Preferencias de la app'},
    'en-US':{title:'App preferences',desc:'General Arydebts options. Your personal information lives in My profile.',language:'Language and region',languaged:'Choose the language and formatting you want to use.',change:'🌐 Change language',close:'Close',settings:'⚙️ App preferences'},
    'pt-BR':{title:'Preferências do app',desc:'Opções gerais do Arydebts. Suas informações pessoais ficam em Meu perfil.',language:'Idioma e região',languaged:'Escolha o idioma e a formatação que deseja usar.',change:'🌐 Alterar idioma',close:'Fechar',settings:'⚙️ Preferências do app'}
  };
  const text=()=>L[(typeof s!=='undefined'&&L[s.locale])?s.locale:'es-US'];
  window.aryV18Settings=()=>{const t=text();if(typeof modal!=='function')return;modal(`<h2>⚙️ ${t.title}</h2><p class="muted">${t.desc}</p><div class="v18-settings"><div class="v18-settingRow"><div><b>${t.language}</b><span class="muted">${t.languaged}</span></div><button class="btn" onclick="closeM();languageMenu()">${t.change}</button></div></div><button class="btn widebtn" onclick="closeM()">${t.close}</button>`)};
  function enhance(){const app=document.getElementById('app');if(!app)return;if(typeof screen!=='undefined'&&screen==='more'){const t=text();const candidates=[...app.querySelectorAll('button')].filter(b=>/Configuraci|Settings|Configuraç|Preferencias de la app|App preferences|Preferências do app/i.test(b.textContent));candidates.forEach(b=>{if(b.textContent!==t.settings)b.textContent=t.settings;b.onclick=window.aryV18Settings;b.removeAttribute('data-v18-settings')});if(!candidates.length){const cards=[...app.querySelectorAll('.card')],host=cards[cards.length-1]||app,b=document.createElement('button');b.className='btn widebtn';b.dataset.v18Settings='1';b.innerHTML=t.settings;b.onclick=window.aryV18Settings;host.appendChild(b)}}}
  const obs=new MutationObserver(()=>requestAnimationFrame(enhance));window.addEventListener('DOMContentLoaded',()=>{enhance();const app=document.getElementById('app');if(app)obs.observe(app,{childList:true,subtree:true})});setTimeout(enhance,0);
})();