(()=>{
const BASE='ary-home-baseline-v29';
function debtNow(){return (s.debts||[]).reduce((a,d)=>a+(Number(d.balance)||0),0)}
function baseline(now){let b=Number(localStorage.getItem(BASE));if(!Number.isFinite(b)||b<0){b=now;localStorage.setItem(BASE,String(b))}return b}
function pctPaid(now,b){return b>0?Math.max(0,Math.min(100,Math.round((b-now)/b*100))):now<=0?100:0}
function monthlyIncome(){const n=Number(s.income)||0;return s.incomeFrequency==='weekly'?n*52/12:s.incomeFrequency==='biweekly'?n*26/12:n}
function localDay(){const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`}
function currentMonthExpenses(){const ym=(typeof aryExpenseDate==='function'?aryExpenseDate():localDay()).slice(0,7),all=s.expenses||[],dated=all.filter(e=>e.date&&String(e.date).slice(0,7)===ym),legacy=all.filter(e=>!e.date);return{total:dated.reduce((a,e)=>a+(Number(e.amount)||0),0),datedCount:dated.length,legacyCount:legacy.length}}
function dueMeta(d){if(!d.due)return'Fecha pendiente';const raw=String(d.due),today=new Date(localDay()+'T00:00:00');let x;if(/^\d{4}-\d{2}-\d{2}$/.test(raw))x=new Date(raw+'T00:00:00');else return raw;const days=Math.round((x-today)/86400000);return days<0?`Vencido hace ${Math.abs(days)} día${Math.abs(days)===1?'':'s'}`:days===0?'Vence hoy':days===1?'Vence mañana':`En ${days} días`}
function upcoming(){const t=localDay(),items=[];(s.debts||[]).forEach(d=>{if(d.due&&d.due>=t)items.push({date:d.due,name:d.name,amount:+d.min||0,icon:d.icon||iconFor(d.name,'deuda'),kind:'Pago mínimo'})});(Array.isArray(s.calendarEvents)?s.calendarEvents:[]).forEach(e=>{if(e.date&&e.date>=t)items.push({date:e.date,name:e.name,amount:+e.amount||0,icon:e.icon||'📌',kind:e.kind==='income'?'Ingreso':e.kind==='reminder'?'Recordatorio':'Pago'})});return items.sort((a,b)=>a.date.localeCompare(b.date)).slice(0,4)}
function renderHome29(){const now=debtNow(),b=baseline(now),p=pctPaid(now,b),paid=Math.max(0,b-now),increase=Math.max(0,now-b),inc=monthlyIncome(),ex=currentMonthExpenses(),mins=(s.debts||[]).reduce((a,d)=>a+(Number(d.min)||0),0),available=inc-ex.total,extra=Math.max(0,available-mins),target=[...(s.debts||[])].filter(d=>(Number(d.balance)||0)>0).sort((a,c)=>(Number(c.apr)||0)-(Number(a.apr)||0))[0],dated=ex.datedCount>0,next=upcoming();return head('Buenos días<br>¡Comandante! 👋','Hoy es un gran día para acercarte a tus metas.')+`<div class="grid"><section class="card full heroCard homeTruth29"><b>Tu progreso real contra la deuda</b><div class="progressBox"><div class="ring" style="--p:${p}"><b>${p}%</b></div><div><span class="muted">Deuda actual</span><div class="kpi">${money(now)}</div><span class="muted">Pagado desde tu punto de partida</span><div class="kpi good">${money(paid)}</div></div></div><small class="muted">Punto de partida registrado: ${money(b)}.</small>${increase?`<div class="homeDebtRise37">⚠️ La deuda actual aumentó ${money(increase)} frente a tu punto de partida. No reinicié tu progreso.</div>`:''}</section><section class="card third"><span class="muted">🟢 Ingreso mensual estimado</span><div class="kpi">${money(inc)}</div></section><section class="card third"><span class="muted">🌸 Gastos de este mes</span><div class="kpi">${money(ex.total)}</div></section><section class="card third"><span class="muted">🔵 Disponible estimado</span><div class="kpi ${available<0?'bad':'good'}">${money(available)}</div></section>${!dated&&ex.legacyCount?`<section class="card full homeDataNote30"><b>📅 Mejora la precisión</b><p class="muted">Tienes ${ex.legacyCount} gasto${ex.legacyCount===1?'':'s'} histórico${ex.legacyCount===1?'':'s'} sin fecha. No los estoy contando como gasto de este mes porque Arydebts no debe inventar cuándo ocurrieron.</p><button class="btn" onclick="go('expenses')">Revisar gastos →</button></section>`:''}<section class="card full notice homeCoach29"><b>${available<0?'⚠️ Los gastos fechados de este mes superan tu ingreso mensual estimado.':'🌈 Cada pequeña decisión hace una gran diferencia.'}</b>${target?`<p class="muted">Prioridad sugerida por interés: <b>${esc(target.name)}</b>${target.apr?` · ${target.apr}% APR`:''}. Después de gastos del mes y pagos mínimos, tu margen extra estimado es <b>${money(extra)}</b>.</p>`:''}</section><section class="card full"><b>Tus próximos movimientos</b><button class="linkBtn" onclick="go('calendar')">Ver calendario ›</button><div class="list">${next.length?next.map(e=>row(e.icon,e.name,`${e.date} · ${e.kind}`,money(e.amount))).join(''):'<p class="muted">No tienes próximos movimientos con fecha.</p>'}</div></section></div>`}
if(typeof screens!=='undefined')screens.home=renderHome29;window.aryHomeV37=renderHome29;
})();