(()=>{
const BASE='ary-home-baseline-v29';
function debtNow(){return (s.debts||[]).reduce((a,d)=>a+(Number(d.balance)||0),0)}
function baseline(now){let b=Number(localStorage.getItem(BASE));if(!Number.isFinite(b)||b<now){b=now;localStorage.setItem(BASE,String(b))}return b}
function pctPaid(now,b){return b>0?Math.max(0,Math.min(100,Math.round((b-now)/b*100))):100}
function monthlyIncome(){const n=Number(s.income)||0;return s.incomeFrequency==='weekly'?n*52/12:s.incomeFrequency==='biweekly'?n*26/12:n}
function monthlyExpenses(){return (s.expenses||[]).reduce((a,e)=>a+(Number(e.amount)||0),0)}
function renderHome29(){const now=debtNow(),b=baseline(now),p=pctPaid(now,b),paid=Math.max(0,b-now),inc=monthlyIncome(),exp=monthlyExpenses(),mins=(s.debts||[]).reduce((a,d)=>a+(Number(d.min)||0),0),available=inc-exp,extra=Math.max(0,available-mins),target=[...(s.debts||[])].filter(d=>(Number(d.balance)||0)>0).sort((a,c)=>(Number(c.apr)||0)-(Number(a.apr)||0))[0];return head('Buenos días<br>¡Comandante! 👋','Hoy es un gran día para acercarte a tus metas.')+`<div class="grid"><section class="card full heroCard homeTruth29"><b>Tu progreso real contra la deuda</b><div class="progressBox"><div class="ring" style="--p:${p}"><b>${p}%</b></div><div><span class="muted">Deuda actual</span><div class="kpi">${money(now)}</div><span class="muted">Pagado desde tu punto de partida</span><div class="kpi good">${money(paid)}</div></div></div><small class="muted">Punto de partida registrado: ${money(b)}. Arydebts ya no usa una deuda fija de demostración para este progreso.</small></section><section class="card third"><span class="muted">🟢 Ingreso mensual estimado</span><div class="kpi">${money(inc)}</div></section><section class="card third"><span class="muted">🌸 Gastos registrados</span><div class="kpi">${money(exp)}</div></section><section class="card third"><span class="muted">🔵 Disponible estimado</span><div class="kpi ${available<0?'bad':'good'}">${money(available)}</div></section><section class="card full notice homeCoach29"><b>${available<0?'⚠️ Tus gastos registrados superan tu ingreso mensual estimado.':'🌈 Cada pequeña decisión hace una gran diferencia.'}</b>${target?`<p class="muted">Prioridad sugerida: <b>${esc(target.name)}</b>${target.apr?` · ${target.apr}% APR`:''}. Después de gastos y mínimos, tu margen extra estimado es <b>${money(extra)}</b>.</p>`:''}</section><section class="card full"><b>Tus próximos pagos</b><button class="linkBtn" onclick="go('calendar')">Ver todos ›</button><div class="list">${s.debts.slice(0,3).map((d,i)=>row(iconFor(d.name,'deuda'),d.name,(d.due||'Próximo pago')+(i===0?' · En 2 días':i===1?' · En 1 semana':' · En 3 semanas'),money(d.min))).join('')}</div></section></div>`}
if(typeof screens!=='undefined')screens.home=renderHome29;window.aryHomeV29=renderHome29;
})();