// Native entry screens and one translation pass for legacy UI copy.
(()=>{
const COPY={
es:{back:'‹ Volver',signup:'Este espacio es tuyo',login:'Qué bueno verte 👋',signupSub:'No tienes que tener tus finanzas perfectas para empezar. Solo cuéntanos dónde estás y avanzamos desde ahí.',loginSub:'Vuelve a tu plan y continúa donde lo dejaste.',name:'¿Cómo quieres que te llamemos?',namePh:'Tu nombre',email:'Correo electrónico',password:'Contraseña',create:'Crear mi espacio',enter:'Entrar',social:'Estos accesos sociales son interfaz de demostración hasta conectar autenticación segura. No te pediremos contraseñas de esas plataformas aquí.',intro:'Empieza a cambiar',life:'tu vida.',introSub:'Vamos a convertir números que hoy pueden sentirse pesados en pasos pequeños y claros.',safe:'Aquí puedes sentirte cómodo.',help:'Si sigues un plan realista, Arydebts te ayudará a ordenar tus finanzas, reducir estrés y acercarte a esa casa, ese carro o esa tranquilidad que quieres construir.',start:'Quiero empezar'},
en:{back:'‹ Back',signup:'This space is yours',login:'Good to see you 👋',signupSub:'Your finances do not have to be perfect to begin. Tell us where you are and we will move forward from there.',loginSub:'Return to your plan and continue where you left off.',name:'What should we call you?',namePh:'Your name',email:'Email address',password:'Password',create:'Create my space',enter:'Sign in',social:'These social sign-ins are a demo until secure authentication is connected. We will not ask for passwords for those platforms here.',intro:'Start changing',life:'your life.',introSub:'We will turn numbers that may feel heavy today into small, clear steps.',safe:'You can feel comfortable here.',help:'With a realistic plan, Arydebts will help you organize your finances, reduce stress, and move closer to the home, car, or peace of mind you want to build.',start:'I want to start'},
pt:{back:'‹ Voltar',signup:'Este espaço é seu',login:'Que bom ver você 👋',signupSub:'Suas finanças não precisam estar perfeitas para começar. Conte onde você está e avançaremos a partir daí.',loginSub:'Volte ao seu plano e continue de onde parou.',name:'Como você quer que a gente te chame?',namePh:'Seu nome',email:'E-mail',password:'Senha',create:'Criar meu espaço',enter:'Entrar',social:'Esses acessos sociais são uma demonstração até conectarmos autenticação segura. Não pediremos as senhas dessas plataformas aqui.',intro:'Comece a mudar',life:'sua vida.',introSub:'Vamos transformar números que hoje podem parecer pesados em passos pequenos e claros.',safe:'Aqui você pode se sentir à vontade.',help:'Com um plano realista, Arydebts ajudará você a organizar suas finanças, reduzir o estresse e se aproximar da casa, carro ou tranquilidade que deseja construir.',start:'Quero começar'}
};
const lang=()=>s.locale==='en-US'?'en':s.locale==='pt-BR'?'pt':'es';
function auth54(mode){const t=COPY[lang()],up=mode==='signup';return `<section class="welcome auth" data-ary-copy><button class="btn" onclick="go('welcome')">${t.back}</button><div class="logoMark grad">↗</div><h1>${up?t.signup:t.login}</h1><p class="muted">${up?t.signupSub:t.loginSub}</p>${up?`<label for="an">${t.name}</label><input id="an" autocomplete="name" placeholder="${t.namePh}">`:''}<label for="ae">${t.email}</label><input id="ae" type="email" autocomplete="email" placeholder="you@example.com"><label for="ap">${t.password}</label><input id="ap" type="password" autocomplete="${up?'new-password':'current-password'}" placeholder="••••••••"><button class="btn primary widebtn" onclick="localAuth('${mode}')">${up?t.create:t.enter}</button><div class="socials"><button class="btn" onclick="socialDemo('Apple')"> Apple</button><button class="btn" onclick="socialDemo('Google')">G Google</button><button class="btn" onclick="socialDemo('Facebook')">f Facebook</button></div><p class="muted">${t.social}</p></section>`}
function intro54(){const t=COPY[lang()];return `<section class="welcome" data-ary-copy>${dots(1)}<div class="heroLogo small">${logo()}</div><h1>${t.intro}<br><span class="grad">${t.life}</span></h1><p>${t.introSub}</p><div class="notice"><b>${t.safe}</b><p>${t.help}</p></div><button class="btn primary widebtn" onclick="go('setupIncome')">${t.start} →</button></section>`}
// Longer entries win. Word boundaries prevent translating parts of Portuguese words.
const EXTRA={
en:{'Esenciales':'Essentials','Nuevo gasto':'New expense','Editar deuda':'Edit debt','Saldo':'Balance','Pago mínimo':'Minimum payment','Fecha de vencimiento':'Due date','Notas (opcional)':'Notes (optional)','APR / interés %':'APR / interest %','Nombre de la deuda':'Debt name','Icono':'Icon','Celular, carro, renta...':'Phone, car, rent...','Escribe el valor':'Enter the amount','Tipo de cambio real se conectará en infraestructura.':'Live exchange rates will be connected in a later phase.','Ej: Últimos 4 dígitos, banco, etc.':'E.g. Last 4 digits, bank, etc.','Saludo personalizado':'Custom greeting','Buenos días, comandante':'Good morning, commander','Idioma / región':'Language / region','Guardar cambios':'Save changes','Categoría':'Category','Cancelar':'Cancel','Escribe valores válidos para la deuda':'Enter valid debt values','Escribe un ingreso válido':'Enter a valid income','Escribe un valor válido':'Enter a valid amount','Icono seleccionado':'Icon selected','Elige el orden de las pestañas inferiores.':'Choose the order of the bottom tabs.','Pregúntame sobre tu situación financiera.':'Ask about your financial situation.','Estoy aquí para ayudarte a entender tus números y tomar una decisión a la vez. En esta demo respondo con reglas locales; después podremos conectar inteligencia más avanzada.':'I am here to help you understand your numbers and take one decision at a time. This demo uses local rules; more advanced intelligence can be connected later.','Escribe tu pregunta...':'Type your question...','Con tus datos actuales, protege primero gastos esenciales y pagos mínimos. Luego usa el excedente para tu deuda prioritaria.':'With your current data, protect essential expenses and minimum payments first. Then use the surplus for your priority debt.','Tu deuda registrada es':'Your recorded debt is','Si tus mínimos están cubiertos, prioriza la tasa APR más alta.':'If minimums are covered, prioritize the highest recorded APR.','Tus gastos registrados suman':'Your recorded expenses total','Tus gastos hormiga son':'Your small recurring expenses total','Hoy':'Today','Mi perfil':'My profile'},
pt:{'Esenciales':'Essenciais','Nuevo gasto':'Novo gasto','Editar deuda':'Editar dívida','Saldo':'Saldo','Pago mínimo':'Pagamento mínimo','Fecha de vencimiento':'Data de vencimento','Notas (opcional)':'Notas (opcional)','APR / interés %':'APR / juros %','Nombre de la deuda':'Nome da dívida','Icono':'Ícone','Celular, carro, renta...':'Celular, carro, aluguel...','Escribe el valor':'Digite o valor','Tipo de cambio real se conectará en infraestructura.':'As taxas de câmbio em tempo real serão conectadas em uma próxima etapa.','Ej: Últimos 4 dígitos, banco, etc.':'Ex.: Últimos 4 dígitos, banco, etc.','Saludo personalizado':'Saudação personalizada','Buenos días, comandante':'Bom dia, comandante','Idioma / región':'Idioma / região','Guardar cambios':'Salvar alterações','Categoría':'Categoria','Cancelar':'Cancelar','Escribe valores válidos para la deuda':'Digite valores válidos para a dívida','Escribe un ingreso válido':'Digite uma renda válida','Escribe un valor válido':'Digite um valor válido','Icono seleccionado':'Ícone selecionado','Elige el orden de las pestañas inferiores.':'Escolha a ordem das abas inferiores.','Pregúntame sobre tu situación financiera.':'Pergunte sobre sua situação financeira.','Estoy aquí para ayudarte a entender tus números y tomar una decisión a la vez. En esta demo respondo con reglas locales; después podremos conectar inteligencia más avanzada.':'Estou aqui para ajudar você a entender seus números e tomar uma decisão por vez. Esta demonstração usa regras locais; depois poderemos conectar inteligência mais avançada.','Escribe tu pregunta...':'Escreva sua pergunta...','Con tus datos actuales, protege primero gastos esenciales y pagos mínimos. Luego usa el excedente para tu deuda prioritaria.':'Com seus dados atuais, proteja primeiro os gastos essenciais e os pagamentos mínimos. Depois use o excedente para a dívida prioritária.','Tu deuda registrada es':'Sua dívida registrada é','Si tus mínimos están cubiertos, prioriza la tasa APR más alta.':'Se os pagamentos mínimos estiverem cobertos, priorize a maior taxa APR registrada.','Tus gastos registrados suman':'Seus gastos registrados somam','Tus gastos hormiga son':'Seus pequenos gastos recorrentes somam','Hoy':'Hoje','Mi perfil':'Meu perfil'}
};
const maps={},patterns={};
for(const l of ['en','pt']){maps[l]={...(window.aryLocaleBase20?.[l]||{}),...(window.aryLocaleRemaining53?.[l]||{}),...EXTRA[l]};const keys=Object.keys(maps[l]).sort((a,b)=>b.length-a.length).map(k=>k.replace(/[.*+?^${}()|[\]\\]/g,'\\$&'));patterns[l]=new RegExp('(?<![\\p{L}\\p{N}])(?:'+keys.join('|')+')(?![\\p{L}\\p{N}])','gu')}
const protectedElement=el=>el?.closest?.('[data-ary-user],[data-ary-copy],[translate="no"],.notranslate,textarea');
function translate54(root=document.body){const l=lang();document.documentElement.lang=l==='pt'?'pt-BR':l==='en'?'en':'es';if(l==='es')return;const replace=value=>String(value||'').replace(patterns[l],match=>maps[l][match]);const walker=document.createTreeWalker(root,NodeFilter.SHOW_TEXT);let n;while(n=walker.nextNode()){if(!n.parentElement||['SCRIPT','STYLE'].includes(n.parentElement.tagName)||protectedElement(n.parentElement))continue;const next=replace(n.nodeValue);if(next!==n.nodeValue)n.nodeValue=next}root.querySelectorAll?.('[placeholder],[title],[aria-label],option').forEach(el=>{if(protectedElement(el))return;for(const attr of ['placeholder','title','aria-label']){if(!el.hasAttribute(attr))continue;const value=el.getAttribute(attr),next=replace(value);if(next!==value)el.setAttribute(attr,next)}})}
window.aryTranslateUI54=translate54;window.aryTranslate=translate54;
screens.signup=()=>auth54('signup');screens.login=()=>auth54('login');screens.intro=intro54;
const HOME_COPY={es:{title:'Personalizar inicio',sub:'Elige el orden de las pestañas inferiores.',done:'Listo',labels:{home:'Inicio',debts:'Deudas',expenses:'Gastos',plan:'Plan',more:'Más'}},en:{title:'Customize home',sub:'Choose the order of the bottom tabs.',done:'Done',labels:{home:'Home',debts:'Debts',expenses:'Expenses',plan:'Plan',more:'More'}},pt:{title:'Personalizar início',sub:'Escolha a ordem das abas inferiores.',done:'Pronto',labels:{home:'Início',debts:'Dívidas',expenses:'Gastos',plan:'Plano',more:'Mais'}}};
window.customizeHome=()=>{const t=HOME_COPY[lang()];modal(`<section data-ary-copy><h2>${t.title}</h2><p class="muted">${t.sub}</p>${s.navOrder.map((key,i)=>`<div class="row"><b>${t.labels[key]||esc(key)}</b><div><button class="btn tiny" onclick="moveNav(${i},-1)">↑</button><button class="btn tiny" onclick="moveNav(${i},1)">↓</button></div></div>`).join('')}<button class="btn widebtn" onclick="closeM()">${t.done}</button></section>`)};
// Static notification labels are app copy, not protected user-entered names.
const oldNotifications=screens.notifications;
screens.notifications=()=>oldNotifications().replaceAll('data-ary-user translate="no"','data-ary-static');
const oldToast=window.toast;window.toast=value=>{const l=lang(),v=l==='es'?value:String(value).replace(patterns[l],m=>maps[l][m]);oldToast(v)};
if(typeof render==='function')render();
})();
