(()=>{
const BASE='ary-debt-start-v54';
const L={es:{title:'Tu progreso',sub:'Aquí solo cuenta lo que realmente registras.',debt:'Deuda actual',paid:'Pagado',progress:'Progreso',history:'Historial de pagos',empty:'Todavía no has registrado pagos. Cuando hagas uno, aparecerá aquí.',add:'Registrar pago',choose:'Deuda',amount:'Monto pagado',date:'Fecha',note:'Nota opcional',notePh:'Ej. Pago mínimo de octubre',save:'Guardar pago',cancel:'Cancelar',invalid:'Ingresa un monto válido',nodebt:'Primero agrega una deuda',saved:'Pago registrado',payment:'Pago',delete:'Eliminar',confirm:'¿Eliminar este pago y devolver el monto al saldo de la deuda?',restored:'Pago eliminado y saldo restaurado',complete:'Deuda pagada 🎉'},en:{title:'Your progress',sub:'Only what you actually record counts here.',debt:'Current debt',paid:'Paid',progress:'Progress',history:'Payment history',empty:'You have not recorded any payments yet. When you make one, it will appear here.',add:'Record payment',choose:'Debt',amount:'Amount paid',date:'Date',note:'Optional note',notePh:'E.g. October minimum payment',save:'Save payment',cancel:'Cancel',invalid:'Enter a valid amount',nodebt:'Add a debt first',saved:'Payment recorded',payment:'Payment',delete:'Delete',confirm:'Delete this payment and return the amount to the debt balance?',restored:'Payment deleted and balance restored',complete:'Debt paid 🎉'},pt:{title:'Seu progresso',sub:'Aqui conta apenas o que você realmente registra.',debt:'Dívida atual',paid:'Pago',progress:'Progresso',history:'Histórico de pagamentos',empty:'Você ainda não registrou pagamentos. Quando fizer um, ele aparecerá aqui.',add:'Registrar pagamento',choose:'Dívida',amount:'Valor pago',date:'Data',note:'Nota opcional',notePh:'Ex. Pagamento mínimo de outubro',save:'Salvar pagamento',cancel:'Cancelar',invalid:'Digite um valor válido',nodebt:'Primeiro adicione uma dívida',saved:'Pagamento registrado',payment:'Pagamento',delete:'Excluir',confirm:'Excluir este pagamento e devolver o valor ao saldo da dívida?',restored:'Pagamento excluído e saldo restaurado',complete:'Dívida paga 🎉'}};
const tx=()=>L[s?.locale==='en-US'?'en':s?.locale==='pt-BR'?'pt':'es'];
const today=()=>{const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`};
const persist=()=>{try{localStorage.setItem(typeof KEY!=='undefined'?KEY:'arydebts-v3',JSON.stringify(s))}catch(e){}};
const debtTotal=()=> (s.debts||[]).reduce((a,d)=>a+(Number(d.balance)||0),0);
const payments=()=>Array.isArray(s.payments)?s.payments:[];
function baseline(){let b=0;try{b=Number(localStorage.getItem(BASE))||0}catch(e){}const current=debtTotal(),paid=payments().reduce((a,p)=>a+(Number(p.amount)||0),0);if(b<=0&&current+paid>0){b=current+paid;try{localStorage.setItem(BASE,String(b))}catch(e){}}return b}
function fmtDate(v){if(!v)return'';const [y,m,d]=String(v).split('-').map(Number);try{return new Intl.DateTimeFormat(s.locale||'es-US',{month:'short',day:'numeric',year:'numeric'}).format(new Date(y,m-1,d))}catch(e){return v}}
window.aryPaymentForm54=function(){const x=tx(),active=(s.debts||[]).filter(d=>(Number(d.balance)||0)>0);if(!active.length)return toast(x.nodebt);modal(`<h2>💸 ${x.add}</h2><label>${x.choose}</label><select id="payDebt54">${active.map(d=>`<option value="${d.id}">${esc(d.name)} · ${money(d.balance)}</option>`).join('')}</select><label>${x.amount}</label><input id="payAmount54" type="number" inputmode="decimal" min="0.01" step="0.01" placeholder="0"><label>${x.date}</label><input id="payDate54" type="date" value="${today()}"><label>${x.note}</label><input id="payNote54" maxlength="120" placeholder="${x.notePh}"><button class="btn primary widebtn" onclick="arySavePayment54()">${x.save}</button><button class="btn widebtn" onclick="closeM()">${x.cancel}</button>`)};
window.arySavePayment54=function(){const x=tx(),id=Number(document.getElementById('payDebt54')?.value),raw=document.getElementById('payAmount54')?.value,amount=Number(raw),date=document.getElementById('payDate54')?.value||today(),note=String(document.getElementById('payNote54')?.value||'').trim(),d=(s.debts||[]).find(z=>Number(z.id)===id);if(!d||!Number.isFinite(amount)||amount<=0)return toast(x.invalid);const applied=Math.min(amount,Number(d.balance)||0);if(applied<=0)return toast(x.invalid);baseline();d.balance=Math.max(0,(Number(d.balance)||0)-applied);if(!Array.isArray(s.payments))s.payments=[];s.payments.push({id:Date.now(),debtId:d.id,debtName:d.name,amount:applied,date,note});persist();closeM();if(typeof render==='function')render();toast(d.balance<=0?x.complete:x.saved)};
window.aryDeletePayment54=function(id){const x=tx(),p=payments().find(z=>Number(z.id)===Number(id));if(!p)return;if(!confirm(x.confirm))return;const d=(s.debts||[]).find(z=>Number(z.id)===Number(p.debtId));if(d)d.balance=(Number(d.balance)||0)+(Number(p.amount)||0);s.payments=payments().filter(z=>Number(z.id)!==Number(id));persist();if(typeof render==='function')render();toast(x.restored)};
function progress54(){const x=tx(),current=debtTotal(),paid=payments().reduce((a,p)=>a+(Number(p.amount)||0),0),start=baseline(),pct=start>0?Math.max(0,Math.min(100,Math.round((1-current/start)*100))):0,history=[...payments()].sort((a,b)=>String(b.date||'').localeCompare(String(a.date||''))||Number(b.id)-Number(a.id));return head(x.title,x.sub)+`<section class="card full"><div class="progressBox"><div class="ring" style="--p:${pct}"><b>${pct}%</b></div><div><span class="muted">${x.debt}</span><div class="kpi">${money(current)}</div><span class="muted">${x.paid}</span><div class="kpi">${money(paid)}</div></div></div><button class="btn primary widebtn" onclick="aryPaymentForm54()">＋ ${x.add}</button></section><section class="card full"><b>${x.history}</b><div class="list">${history.length?history.map(p=>row('💸',p.debtName||x.payment,`${fmtDate(p.date)}${p.note?' · '+p.note:''}`,money(p.amount),`<div class="rowActions"><button class="btn tiny dangerBtn" onclick="aryDeletePayment54(${p.id})">${x.delete}</button></div>`)).join(''):`<p class="muted">${x.empty}</p>`}</div></section>`}
if(!Array.isArray(s.payments))s.payments=[];
if(typeof screens!=='undefined')screens.progress=progress54;
window.aryProgress54=progress54;
})();