(()=>{
const L={es:{title:'Tu progreso',sub:'Aquí solo cuenta lo que realmente registras.',debt:'Deuda actual',paid:'Pagos registrados',progress:'Progreso',history:'Historial de pagos',empty:'Todavía no has registrado pagos. Cuando hagas uno, aparecerá aquí.',add:'Registrar pago',edit:'Editar',editTitle:'Editar pago',choose:'Deuda',amount:'Monto pagado',date:'Fecha',note:'Nota opcional',notePh:'Ej. Pago mínimo de octubre',save:'Guardar pago',saveChanges:'Guardar cambios',cancel:'Cancelar',invalid:'Ingresa un monto válido',nodebt:'Primero agrega una deuda',saved:'Pago registrado',updated:'Pago actualizado',payment:'Pago',delete:'Eliminar',confirm:'¿Eliminar este pago y devolver el monto al saldo de la deuda?',restored:'Pago eliminado y saldo restaurado',complete:'Deuda pagada 🎉',noProgress:'Tu porcentaje aparecerá cuando registres pagos reales.'},en:{title:'Your progress',sub:'Only what you actually record counts here.',debt:'Current debt',paid:'Recorded payments',progress:'Progress',history:'Payment history',empty:'You have not recorded any payments yet. When you make one, it will appear here.',add:'Record payment',edit:'Edit',editTitle:'Edit payment',choose:'Debt',amount:'Amount paid',date:'Date',note:'Optional note',notePh:'E.g. October minimum payment',save:'Save payment',saveChanges:'Save changes',cancel:'Cancel',invalid:'Enter a valid amount',nodebt:'Add a debt first',saved:'Payment recorded',updated:'Payment updated',payment:'Payment',delete:'Delete',confirm:'Delete this payment and return the amount to the debt balance?',restored:'Payment deleted and balance restored',complete:'Debt paid 🎉',noProgress:'Your percentage will appear after you record real payments.'},pt:{title:'Seu progresso',sub:'Aqui conta apenas o que você realmente registra.',debt:'Dívida atual',paid:'Pagamentos registrados',progress:'Progresso',history:'Histórico de pagamentos',empty:'Você ainda não registrou pagamentos. Quando fizer um, ele aparecerá aqui.',add:'Registrar pagamento',edit:'Editar',editTitle:'Editar pagamento',choose:'Dívida',amount:'Valor pago',date:'Data',note:'Nota opcional',notePh:'Ex. Pagamento mínimo de outubro',save:'Salvar pagamento',saveChanges:'Salvar alterações',cancel:'Cancelar',invalid:'Digite um valor válido',nodebt:'Primeiro adicione uma dívida',saved:'Pagamento registrado',updated:'Pagamento atualizado',payment:'Pagamento',delete:'Excluir',confirm:'Excluir este pagamento e devolver o valor ao saldo da dívida?',restored:'Pagamento excluído e saldo restaurado',complete:'Dívida paga 🎉',noProgress:'Sua porcentagem aparecerá quando você registrar pagamentos reais.'}};
const tx=()=>L[s?.locale==='en-US'?'en':s?.locale==='pt-BR'?'pt':'es'];
const today=()=>{const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`};
const persist=()=>{try{localStorage.setItem(typeof KEY!=='undefined'?KEY:'arydebts-v3',JSON.stringify(s))}catch(e){}};
const debtTotal=()=> (s.debts||[]).reduce((a,d)=>a+(Number(d.balance)||0),0);
const payments=()=>Array.isArray(s.payments)?s.payments:[];
const paidTotal=()=>payments().reduce((a,p)=>a+(Number(p.amount)||0),0);
function realProgress(){const current=debtTotal(),paid=paidTotal(),start=current+paid;return{current,paid,start,pct:start>0&&paid>0?Math.max(0,Math.min(100,Math.round(paid/start*100))):null}}
function fmtDate(v){if(!v)return'';const [y,m,d]=String(v).split('-').map(Number);try{return new Intl.DateTimeFormat(s.locale||'es-US',{month:'short',day:'numeric',year:'numeric'}).format(new Date(y,m-1,d))}catch(e){return v}}
window.aryApplyPayment54=function({debtId,amount,date,note=''}){const x=tx(),d=(s.debts||[]).find(z=>Number(z.id)===Number(debtId)),n=Number(amount);if(!d||!Number.isFinite(n)||n<=0)return{ok:false,message:x.invalid};const balance=Number(d.balance)||0,applied=Math.min(n,balance);if(applied<=0)return{ok:false,message:x.invalid};d.balance=Math.max(0,balance-applied);if(!Array.isArray(s.payments))s.payments=[];const payment={id:Date.now(),debtId:d.id,debtName:d.name,amount:applied,date:date||today(),note:String(note||'').trim()};s.payments.push(payment);persist();return{ok:true,payment,debt:d,applied,complete:d.balance<=0,message:d.balance<=0?x.complete:x.saved}};
window.aryPaymentForm54=function(preselectId=null){const x=tx(),active=(s.debts||[]).filter(d=>(Number(d.balance)||0)>0);if(!active.length)return toast(x.nodebt);modal(`<h2>💸 ${x.add}</h2><label>${x.choose}</label><select id="payDebt54">${active.map(d=>`<option value="${d.id}" ${Number(d.id)===Number(preselectId)?'selected':''}>${esc(d.name)} · ${money(d.balance)}</option>`).join('')}</select><label>${x.amount}</label><input id="payAmount54" type="number" inputmode="decimal" min="0.01" step="0.01" placeholder="0"><label>${x.date}</label><input id="payDate54" type="date" value="${today()}"><label>${x.note}</label><input id="payNote54" maxlength="120" placeholder="${x.notePh}"><button class="btn primary widebtn" onclick="arySavePayment54()">${x.save}</button><button class="btn widebtn" onclick="closeM()">${x.cancel}</button>`)};
window.arySavePayment54=function(){const x=tx(),id=Number(document.getElementById('payDebt54')?.value),raw=document.getElementById('payAmount54')?.value,amount=Number(raw),date=document.getElementById('payDate54')?.value||today(),note=String(document.getElementById('payNote54')?.value||'').trim();const result=window.aryApplyPayment54({debtId:id,amount,date,note});if(!result.ok)return toast(result.message||x.invalid);closeM();if(typeof render==='function')render();toast(result.message)};
window.aryEditPayment54=function(id){const x=tx(),p=payments().find(z=>Number(z.id)===Number(id));if(!p)return;const originalDebt=(s.debts||[]).find(d=>Number(d.id)===Number(p.debtId));if(!originalDebt)return toast(x.invalid);const choices=(s.debts||[]).filter(d=>Number(d.id)===Number(p.debtId)||(Number(d.balance)||0)>0);modal(`<h2>💸 ${x.editTitle}</h2><label>${x.choose}</label><select id="editPayDebt54">${choices.map(d=>`<option value="${d.id}" ${Number(d.id)===Number(p.debtId)?'selected':''}>${esc(d.name)} · ${money((Number(d.balance)||0)+(Number(d.id)===Number(p.debtId)?Number(p.amount)||0:0))}</option>`).join('')}</select><label>${x.amount}</label><input id="editPayAmount54" type="number" inputmode="decimal" min="0.01" step="0.01" value="${Number(p.amount)||0}"><label>${x.date}</label><input id="editPayDate54" type="date" value="${p.date||today()}"><label>${x.note}</label><input id="editPayNote54" maxlength="120" value="${esc(p.note||'')}" placeholder="${x.notePh}"><button class="btn primary widebtn" onclick="arySaveEditedPayment54(${p.id})">${x.saveChanges}</button><button class="btn widebtn" onclick="closeM()">${x.cancel}</button>`)};
window.arySaveEditedPayment54=function(id){const x=tx(),p=payments().find(z=>Number(z.id)===Number(id));if(!p)return;const oldDebt=(s.debts||[]).find(d=>Number(d.id)===Number(p.debtId)),newDebtId=Number(document.getElementById('editPayDebt54')?.value),newDebt=(s.debts||[]).find(d=>Number(d.id)===newDebtId),raw=document.getElementById('editPayAmount54')?.value,n=Number(raw),date=document.getElementById('editPayDate54')?.value||today(),note=String(document.getElementById('editPayNote54')?.value||'').trim();if(!oldDebt||!newDebt||!Number.isFinite(n)||n<=0)return toast(x.invalid);const oldAmount=Number(p.amount)||0,available=(Number(newDebt.balance)||0)+(Number(newDebt.id)===Number(oldDebt.id)?oldAmount:0),applied=Math.min(n,available);if(applied<=0)return toast(x.invalid);oldDebt.balance=(Number(oldDebt.balance)||0)+oldAmount;newDebt.balance=Math.max(0,(Number(newDebt.balance)||0)-applied);Object.assign(p,{debtId:newDebt.id,debtName:newDebt.name,amount:applied,date,note});persist();closeM();if(typeof render==='function')render();toast(newDebt.balance<=0?x.complete:x.updated)};
window.aryDeletePayment54=function(id){const x=tx(),p=payments().find(z=>Number(z.id)===Number(id));if(!p)return;if(!confirm(x.confirm))return;const d=(s.debts||[]).find(z=>Number(z.id)===Number(p.debtId));if(d)d.balance=(Number(d.balance)||0)+(Number(p.amount)||0);s.payments=payments().filter(z=>Number(z.id)!==Number(id));persist();if(typeof render==='function')render();toast(x.restored)};
function progress54(){const x=tx(),r=realProgress(),history=[...payments()].sort((a,b)=>String(b.date||'').localeCompare(String(a.date||''))||Number(b.id)-Number(a.id));const ring=r.pct===null?`<div class="ring" style="--p:0"><b>—</b></div>`:`<div class="ring" style="--p:${r.pct}"><b>${r.pct}%</b></div>`;return head(x.title,x.sub)+`<section class="card full"><div class="progressBox">${ring}<div><span class="muted">${x.debt}</span><div class="kpi">${money(r.current)}</div><span class="muted">${x.paid}</span><div class="kpi">${money(r.paid)}</div></div></div>${r.pct===null?`<p class="muted">${x.noProgress}</p>`:''}<button class="btn primary widebtn" onclick="aryPaymentForm54()">＋ ${x.add}</button></section><section class="card full"><b>${x.history}</b><div class="list">${history.length?history.map(p=>row('💸',p.debtName||x.payment,`${fmtDate(p.date)}${p.note?' · '+p.note:''}`,money(p.amount),`<div class="rowActions"><button class="btn tiny" onclick="aryEditPayment54(${p.id})">${x.edit}</button><button class="btn tiny dangerBtn" onclick="aryDeletePayment54(${p.id})">${x.delete}</button></div>`)).join(''):`<p class="muted">${x.empty}</p>`}</div></section>`}
if(!Array.isArray(s.payments))s.payments=[];
if(typeof screens!=='undefined')screens.progress=progress54;
window.aryProgress54=progress54;
window.aryRealDebtProgress54=realProgress;
})();