(()=>{
const PHOTO='ary-profile-photo-v46';
const getPhoto=()=>{try{return localStorage.getItem(PHOTO)||''}catch(e){return''}};
function photoUI(){const p=getPhoto();return `<div class="profilePhoto46">${p?`<img src="${p}" alt="Foto de perfil">`:'<span>👤</span>'}</div><div class="profilePhotoActions46"><button class="btn" onclick="aryChoosePhoto46()">📷 Elegir foto</button><button class="btn" onclick="aryTakeSelfie46()">🤳 Tomar selfie</button>${p?'<button class="btn dangerBtn" onclick="aryRemovePhoto46()">Quitar foto</button>':''}</div><input id="aryPhoto46" type="file" accept="image/*" hidden onchange="arySavePhoto46(this)"><input id="arySelfie46" type="file" accept="image/*" capture="user" hidden onchange="arySavePhoto46(this)">`}
window.aryChoosePhoto46=()=>document.getElementById('aryPhoto46')?.click();
window.aryTakeSelfie46=()=>document.getElementById('arySelfie46')?.click();
window.arySavePhoto46=input=>{const f=input.files&&input.files[0];if(!f)return;if(!f.type.startsWith('image/'))return toast('Elige una imagen válida');if(f.size>5*1024*1024)return toast('La foto debe pesar menos de 5 MB');const r=new FileReader();r.onload=()=>{try{localStorage.setItem(PHOTO,String(r.result));toast('Foto actualizada');aryProfile46()}catch(e){toast('No pudimos guardar esa foto en este dispositivo')}};r.readAsDataURL(f)};
window.aryRemovePhoto46=()=>{try{localStorage.removeItem(PHOTO)}catch(e){}aryProfile46()};
window.arySaveProfile46=()=>{const n=document.getElementById('aryName46')?.value.trim();if(n)s.name=n;const e=document.getElementById('aryEmail46')?.value.trim();if(typeof profile==='object'&&profile){profile.name=n||profile.name;profile.email=e||profile.email;try{localStorage.setItem(typeof AUTH!=='undefined'?AUTH:'arydebts-profile',JSON.stringify(profile))}catch(x){}}save();closeM();toast('Perfil actualizado')};
window.aryProfile46=()=>{const p=typeof profile==='object'&&profile?profile:{},name=String(s.name||p.name||''),email=String(p.email||'');modal(`<h2>👤 Mi perfil</h2><p class="muted">Tu identidad y tus datos personales de Arydebts.</p>${photoUI()}<div class="profileSection46"><b>Información personal</b><label>Nombre</label><input id="aryName46" value="${esc(name)}" placeholder="Tu nombre"><label>Correo</label><input id="aryEmail46" type="email" value="${esc(email)}" placeholder="tucorreo@ejemplo.com"><button class="btn primary widebtn" onclick="arySaveProfile46()">Guardar perfil</button></div><div class="profileSecurity46"><b>🛡️ Privacidad y seguridad</b><p>En esta versión, tus datos financieros se guardan localmente en este dispositivo. Arydebts no debe prometer cifrado o protección de servidor hasta que conectemos un backend seguro.</p><button class="btn widebtn" onclick="arySecurity46()">Ver seguridad y privacidad</button></div><button class="btn widebtn" onclick="closeM()">Cerrar</button>`)};
window.arySecurity46=()=>modal(`<h2>🛡️ Seguridad y privacidad</h2><p><b>Datos locales:</b> actualmente tu información financiera principal vive en el almacenamiento de este navegador.</p><p><b>Importante:</b> esto no equivale a cifrado de extremo a extremo ni a una cuenta sincronizada en la nube.</p><p class="muted">Cuando añadamos autenticación y backend, aquí podremos incluir contraseña, sesiones, dispositivos, recuperación de cuenta y controles de privacidad reales.</p><button class="btn widebtn" onclick="aryProfile46()">‹ Volver a mi perfil</button>`)};
function enhance(){if(typeof screen==='undefined'||screen!=='profile')return;const app=document.getElementById('app');if(!app)return;const buttons=[...app.querySelectorAll('button')];buttons.forEach(b=>{if(/^⚙️?\s*Configuraci/i.test(b.textContent.trim())){b.textContent='✏️ Editar mi perfil';b.onclick=window.aryProfile46}});const card=app.querySelector('.card');if(card&&!card.querySelector('.profileAvatar46')){const p=getPhoto(),box=document.createElement('button');box.className='profileAvatar46';box.type='button';box.onclick=window.aryProfile46;box.innerHTML=p?`<img src="${p}" alt="Foto de perfil">`:'👤';card.prepend(box)}}
const o=new MutationObserver(()=>requestAnimationFrame(enhance));addEventListener('DOMContentLoaded',()=>{enhance();const a=document.getElementById('app');if(a)o.observe(a,{childList:true,subtree:true})});setTimeout(enhance,0);
})();