(()=>{
const text=()=>({es:{title:'Verificación antibot',retry:'Completa la verificación para continuar.',unavailable:'La verificación no está disponible. Intenta más tarde.',creating:'Creando tu espacio…',failed:'No pudimos verificar el registro. Intenta otra vez.'},en:{title:'Bot verification',retry:'Complete verification to continue.',unavailable:'Verification is unavailable. Try again later.',creating:'Creating your space…',failed:'We could not verify registration. Try again.'},pt:{title:'Verificação antibot',retry:'Conclua a verificação para continuar.',unavailable:'A verificação está indisponível. Tente novamente mais tarde.',creating:'Criando seu espaço…',failed:'Não foi possível verificar o cadastro. Tente novamente.'}}[s.locale==='en-US'?'en':s.locale==='pt-BR'?'pt':'es']);
const config=()=>window.aryUIConfig72||{},configured=()=>!!(config().turnstileSiteKey||config().registrationEndpoint);
const endpoint=()=>{try{const u=new URL(config().registrationEndpoint);return u.protocol==='https:'&&!u.username&&!u.password?u.href:''}catch(e){return''}};
let token='',widget=null,loading=null,busy=false;
function load(){if(window.turnstile)return Promise.resolve(window.turnstile);if(loading)return loading;loading=new Promise((resolve,reject)=>{const script=document.createElement('script');script.src='https://challenges.cloudflare.com/turnstile/v0/api.js?render=explicit';script.async=true;script.onload=()=>window.turnstile?resolve(window.turnstile):reject(new Error('widget'));script.onerror=()=>reject(new Error('load'));document.head.appendChild(script)});return loading}
function mount(){if(screen!=='signup'||!configured())return;const host=document.querySelector('#app .auth');if(!host||host.querySelector('#captcha72'))return;const box=document.createElement('div');box.id='captcha72';box.className='captcha72';box.setAttribute('aria-label',text().title);const button=host.querySelector('[onclick*="localAuth"]');host.insertBefore(box,button);token='';if(!endpoint()||!config().turnstileSiteKey){box.textContent=text().unavailable;return}load().then(api=>{if(!box.isConnected)return;if(widget!==null)try{api.remove(widget)}catch(e){}widget=api.render(box,{sitekey:config().turnstileSiteKey,action:'signup',theme:document.documentElement.dataset.aryTheme==='light'?'light':'dark',language:s.locale==='pt-BR'?'pt':s.locale==='en-US'?'en':'es',callback:value=>{token=value},'expired-callback':()=>{token=''},'error-callback':()=>{token=''}})}).catch(()=>{if(box.isConnected)box.textContent=text().unavailable})}
const authBefore=window.localAuth;window.localAuth=async mode=>{if(mode!=='signup'||!configured())return authBefore(mode);if(busy)return;if(!endpoint()||!config().turnstileSiteKey)return toast(text().unavailable);if(!token)return toast(text().retry);const name=document.getElementById('an')?.value.trim(),email=document.getElementById('ae')?.value.trim(),password=document.getElementById('ap')?.value||'';if(!name||!email||!password)return authBefore(mode);busy=true;const submitted=token;token='';const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),15000);try{const response=await fetch(endpoint(),{method:'POST',headers:{'Content-Type':'application/json'},credentials:'include',signal:controller.signal,body:JSON.stringify({name,email,password,token:submitted})});const body=await response.json();if(!response.ok||body.success!==true)throw new Error('verification');if(screen==='signup'){document.getElementById('an').value=name;document.getElementById('ae').value=email;document.getElementById('ap').value=password;return authBefore(mode)}}catch(e){toast(text().failed);if(window.turnstile&&widget!==null)window.turnstile.reset(widget)}finally{clearTimeout(timer);busy=false}};
const before=window.render;window.render=()=>{if(screen!=='signup'&&widget!==null&&window.turnstile){try{window.turnstile.remove(widget)}catch(e){}widget=null;token=''}const result=before();mount();return result};render();
})();
