(()=>{
const monthIncome=()=>{const n=+s.income||0;return s.incomeFrequency==='weekly'?n*52/12:s.incomeFrequency==='biweekly'?n*26/12:n};
const day=()=>{const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`};
const monthSpend=()=>{const ym=day().slice(0,7);return (s.expenses||[]).filter(e=>e.date&&String(e.date).slice(0,7)===ym).reduce((a,e)=>a+(+e.amount||0),0)};
function nextDue(){const t=day(),a=[];(s.debts||[]).forEach(d=>{if(d.due&&d.due>=t&&+d.min>0)a.push({date:d.due,name:d.name,amount:+d.min})});(s.calendarEvents||[]).forEach(e=>{if(e.date&&e.date>=t&&e.kind!=='income'&&+e.amount>0)a.push({date:e.date,name:e.name,amount:+e.amount})});return a.sort((x,y)=>x.date.localeCompare(y.date))[0]||null}
function incomeForm(){modal(`<h2>💰 Mis ingresos</h2><p class="muted">Este dato alimenta tu disponible, tu plan y las recomendaciones de Arydebts.</p><label>Ingreso</label><input id="inc45" type="number" min="0" step="0.01" inputmode="decimal" value="${+s.income||0}"><label>Frecuencia</label><select id="freq45"><option value="weekly" ${s.incomeFrequency==='weekly'?'selected':''}>Semanal</option><option value="biweekly" ${s.incomeFrequency==='biweekly'?'selected':''}>Quincenal</option><option value="monthly" ${s.incomeFrequency==='monthly'?'selected':''}>Mensual</option></select><button class="btn primary widebtn" onclick="arySaveIncome45()">Guardar</button><button class="btn widebtn" onclick="closeM()">Cancelar</button>`)}
window.arySaveIncome45=()=>{const n=+document.getElementById('inc45').value;if(!Number.isFinite(n)||n<0)return toast('Ingresa un valor válido');s.income=n;s.incomeFrequency=document.getElementById('freq45').value;closeM();save()};
function available(){const i=monthIncome(),e=monthSpend(),m=(s.debts||[]).reduce((a,d)=>a+(+d.min||0),0),n=i-e-m;modal(`<h2>🔵 Disponible estimado</h2><div class="list">${row('💰','Ingreso mensual','Según tu frecuencia',money(i))}${row('🌸','Gastos del mes','Con fecha registrada',money(e))}${row('💳','Pagos mínimos','Deudas actuales',money(m))}</div><div class="kpi ${n<0?'bad':'good'}">${money(n)}</div><button class="btn primary widebtn" onclick="closeM();go('plan')">Ver mi plan</button><button class="btn widebtn" onclick="closeM()">Cerrar</button>`)}
function home(){if(screen!=='home')return;const app=document.getElementById('app');if(!app)return;[...app.querySelectorAll('.card.third')].forEach(c=>{const x=c.textContent||'';let fn=null;if(/Ingreso/i.test(x))fn=incomeForm;else if(/Gastos/i.test(x))fn=()=>go('expenses');else if(/Disponible/i.test(x))fn=available;if(fn){c.classList.add('tap45');c.tabIndex=0;c.setAttribute('role','button');c.onclick=fn;c.onkeydown=e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();fn()}}}});const p=app.querySelector('.homeTruth29');if(p){p.classList.add('tap45');p.onclick=()=>go('debts');p.tabIndex=0}const q=app.querySelector('.homeCoach29');if(q){q.classList.add('tap45');q.onclick=()=>go('plan');q.tabIndex=0}}
function verdict(name,price){const i=monthIncome(),e=monthSpend(),m=(s.debts||[]).reduce((a,d)=>a+(+d.min||0),0),free=i-e-m,after=free-price,due=nextDue();if(i<=0)return['NO','🔴 No lo compres todavía.','Primero configura tus ingresos. Sin ese dato Arydebts no puede demostrar que la compra es segura.',free,after];if(free<=0||after<0)return['NO','🔴 No lo compres ahora.',`La compra de ${money(price)} dejaría tu margen estimado en ${money(after)}.`,free,after];if(due&&price>Math.max(10,free*.05))return['NO','🔴 Mejor no lo compres ahora.',`Tienes ${money(due.amount)} de ${esc(due.name)} programados para ${due.date}. Primero protege ese pago.`,free,after];if(price>free*.12||price/i>.03)return['NO','🟠 No es buen momento para comprarlo.',`${money(price)} consume demasiado de tu margen actual de ${money(free)}.`,free,after];return['YES','🟢 Sí, cabe en tu plan.',`Después de comprar ${esc(name||'esto')} conservarías aproximadamente ${money(after)} de margen estimado.`,free,after]}
function buy(){const app=document.getElementById('app');if(!app)return;const h=[...app.querySelectorAll('h1')].find(x=>/Puedo comprar/i.test(x.textContent));if(!h)return;const card=app.querySelector('.card');if(!card||card.dataset.v45)return;const ins=card.querySelectorAll('input'),btn=[...card.querySelectorAll('button')].find(b=>/Analizar/i.test(b.textContent));if(ins.length<2||!btn)return;card.dataset.v45='1';btn.textContent='Decidir por mí con mis números';btn.onclick=()=>{const price=Number(String(ins[1].value).replace(',','.'));if(!(price>0))return toast('Escribe un precio válido');const v=verdict(ins[0].value.trim(),price);const old=card.querySelector('.buy45');if(old)old.remove();card.insertAdjacentHTML('beforeend',`<div class="buy45 ${v[0]==='YES'?'yes':'no'}"><b>${v[1]}</b><p>${v[2]}</p><small>Margen antes: ${money(v[3])} · después: ${money(v[4])}</small></div>`)} }
function enhance(){home();buy()}const o=new MutationObserver(()=>requestAnimationFrame(enhance));addEventListener('DOMContentLoaded',()=>{enhance();const a=document.getElementById('app');if(a)o.observe(a,{childList:true,subtree:true})});setTimeout(enhance,0);
})();