(()=>{
const UI='ary-ui-v72',NOTE='ary-self-message-v72',FEEDBACK='ary-feedback-v72';
const fmtDate=value=>{const date=new Date(String(value)+'T12:00:00');return Number.isFinite(date.getTime())?new Intl.DateTimeFormat(s.locale,{dateStyle:'medium'}).format(date):'—'};
const language=()=>s.locale==='en-US'?'en':s.locale==='pt-BR'?'pt':'es';
const W={es:{hide:'Ocultar mis montos',show:'Mostrar mis montos',hidden:'Montos ocultos',visible:'Montos visibles',search:'Buscar en Arydebts',searchHint:'Busca una sección, deuda o gasto',noResults:'No encontramos resultados',access:'Accesibilidad y estilo',size:'Tamaño de letra',colors:'Colores de la app',brand:'Colores del título Arydebts',normal:'Normal',large:'Grande',larger:'Más grande',largest:'Muy grande',season:'Temporada automática',ocean:'Océano',violet:'Violeta',amber:'Atardecer',forest:'Bosque',reset:'Restablecer estilo',support:'Apoyo',supportSub:'Ayúdanos a seguir construyendo Arydebts.',donate:'Apoyar el proyecto',soon:'Las donaciones estarán disponibles pronto.',free:'Tu apoyo es voluntario. Puedes seguir usando la app sin donar.',announcements:'Centro de anuncios',events:'Eventos y celebraciones',feedback:'Comentarios',feedbackHint:'¿Qué mejorarías? No incluyas contraseñas ni datos financieros.',saveComment:'Guardar comentario',shareComment:'Preparar envío al proyecto',localFeedback:'Guardado en este navegador. Tú decides si lo envías al proyecto.',emptyFeedback:'Tu opinión nos ayuda a mejorar.',saved:'Guardado',delete:'Eliminar',note:'Un mensaje para ti',noteHint:'Ej. Un paso a la vez: estoy construyendo mi tranquilidad.',save:'Guardar',close:'Cerrar',editAmounts:'Muestra tus montos para editarlos.',progress:'Tu progreso hacia la libertad financiera',start:'Deuda actual + pagos registrados',remaining:'Saldo restante',paid:'Has pagado',emptyProgress:'Tu progreso empieza con tu primer pago registrado.',motivations:['El sacrificio de hoy es la tranquilidad de tu mañana.','Decirle “no” a un antojo hoy es decirle “sí” a tu libertad financiera del futuro.','No importa qué tan lento vayas: cada mes puedes acercarte más a la meta.','Tu pasado financiero no define tu futuro; tus decisiones de hoy sí.'],updates:['Ahora puedes ocultar tus montos con el ojito.','Busca tus deudas, gastos y apartados desde un solo lugar.','Personaliza la letra, los colores y tu mensaje personal.'],today:'Hoy',tomorrow:'Mañana',days:'días',annual:'Celebraciones anuales según tu región',world:'Ver agenda mundial',space:'Ver eventos de NASA',calendar:'Mi calendario',newyear:'Año Nuevo',halloween:'Halloween',christmas:'Navidad',independence:'Independencia',source:'Fuente oficial',feedbackReview:'Revisa y publica tu comentario en GitHub. Guardarlo aquí no lo envía.',inProgress:'Progreso basado en pagos registrados',go:'Abrir'},
en:{hide:'Hide my amounts',show:'Show my amounts',hidden:'Amounts hidden',visible:'Amounts visible',search:'Search Arydebts',searchHint:'Find a section, debt or expense',noResults:'No results found',access:'Accessibility and style',size:'Text size',colors:'App colors',brand:'Arydebts title colors',normal:'Normal',large:'Large',larger:'Larger',largest:'Extra large',season:'Automatic seasonal colors',ocean:'Ocean',violet:'Violet',amber:'Sunset',forest:'Forest',reset:'Reset style',support:'Support',supportSub:'Help us keep building Arydebts.',donate:'Support the project',soon:'Donations will be available soon.',free:'Support is voluntary. You can keep using the app without donating.',announcements:'Announcement center',events:'Events and celebrations',feedback:'Feedback',feedbackHint:'What would you improve? Do not include passwords or financial data.',saveComment:'Save feedback',shareComment:'Prepare submission to the project',localFeedback:'Saved in this browser. You decide whether to send it to the project.',emptyFeedback:'Your opinion helps us improve.',saved:'Saved',delete:'Delete',note:'A message to yourself',noteHint:'E.g. One step at a time: I am building my peace of mind.',save:'Save',close:'Close',editAmounts:'Show your amounts to edit them.',progress:'Your progress toward financial freedom',start:'Current debt + recorded payments',remaining:'Remaining balance',paid:'You have paid',emptyProgress:'Progress starts with your first recorded payment.',motivations:['Today’s sacrifice is tomorrow’s peace of mind.','Saying “no” to an impulse today means saying “yes” to future financial freedom.','No matter how slowly you move, each month can bring you closer to your goal.','Your financial past does not define your future; today’s decisions do.'],updates:['You can now hide your amounts with the eye button.','Find debts, expenses and sections in one place.','Personalize text size, colors and a message to yourself.'],today:'Today',tomorrow:'Tomorrow',days:'days',annual:'Annual celebrations for your selected region',world:'View world calendar',space:'View NASA events',calendar:'My calendar',newyear:'New Year',halloween:'Halloween',christmas:'Christmas',independence:'Independence',source:'Official source',feedbackReview:'Review and publish your feedback on GitHub. Saving it here does not send it.',inProgress:'Progress based on recorded payments',go:'Open'},
pt:{hide:'Ocultar meus valores',show:'Mostrar meus valores',hidden:'Valores ocultos',visible:'Valores visíveis',search:'Buscar no Arydebts',searchHint:'Encontre uma seção, dívida ou gasto',noResults:'Nenhum resultado encontrado',access:'Acessibilidade e estilo',size:'Tamanho da letra',colors:'Cores do app',brand:'Cores do título Arydebts',normal:'Normal',large:'Grande',larger:'Maior',largest:'Muito grande',season:'Cores automáticas da temporada',ocean:'Oceano',violet:'Violeta',amber:'Pôr do sol',forest:'Floresta',reset:'Restaurar estilo',support:'Apoio',supportSub:'Ajude a continuar construindo o Arydebts.',donate:'Apoiar o projeto',soon:'As doações estarão disponíveis em breve.',free:'Seu apoio é voluntário. Você pode usar o app sem doar.',announcements:'Central de anúncios',events:'Eventos e celebrações',feedback:'Comentários',feedbackHint:'O que você melhoraria? Não inclua senhas nem dados financeiros.',saveComment:'Salvar comentário',shareComment:'Preparar envio ao projeto',localFeedback:'Salvo neste navegador. Você decide se envia ao projeto.',emptyFeedback:'Sua opinião nos ajuda a melhorar.',saved:'Salvo',delete:'Excluir',note:'Uma mensagem para você',noteHint:'Ex. Um passo de cada vez: estou construindo minha tranquilidade.',save:'Salvar',close:'Fechar',editAmounts:'Mostre seus valores para editá-los.',progress:'Seu progresso rumo à liberdade financeira',start:'Dívida atual + pagamentos registrados',remaining:'Saldo restante',paid:'Você pagou',emptyProgress:'Seu progresso começa com o primeiro pagamento registrado.',motivations:['O sacrifício de hoje é a tranquilidade de amanhã.','Dizer “não” a um desejo hoje é dizer “sim” à liberdade financeira do futuro.','Não importa o ritmo: a cada mês você pode se aproximar da meta.','Seu passado financeiro não define seu futuro; suas decisões de hoje sim.'],updates:['Agora você pode ocultar os valores com o botão de olho.','Encontre dívidas, gastos e seções em um só lugar.','Personalize a letra, as cores e sua mensagem pessoal.'],today:'Hoje',tomorrow:'Amanhã',days:'dias',annual:'Celebrações anuais da região escolhida',world:'Ver agenda mundial',space:'Ver eventos da NASA',calendar:'Meu calendário',newyear:'Ano Novo',halloween:'Halloween',christmas:'Natal',independence:'Independência',source:'Fonte oficial',feedbackReview:'Revise e publique seu comentário no GitHub. Salvar aqui não o envia.',inProgress:'Progresso baseado em pagamentos registrados',go:'Abrir'}};
W.es.contrast='Alto contraste';W.en.contrast='High contrast';W.pt.contrast='Alto contraste';
const extra72={es:['Cada abono, por pequeño que sea, es un paso hacia tu libertad.','No pagas una deuda; compras tu paz mental y tu futuro.','Dejar de pagar intereses es como recibir un aumento de sueldo.','No dejes que el ayer ocupe demasiado espacio en tu hoy.','Una dificultad también puede abrir una oportunidad.','Aprender de un tropiezo te ayuda a dar el siguiente paso.','Fijar una meta es empezar a construir tu futuro.','Un paso a la vez: hoy también cuenta.'],en:['Every payment, however small, is a step toward freedom.','Paying down debt buys peace of mind and a better future.','Paying less interest feels like getting a raise.','Leave room for today instead of dwelling on yesterday.','A challenge can also open a new opportunity.','Learning from a setback helps you take the next step.','Setting a goal starts building your future.','One step at a time: today counts too.'],pt:['Cada pagamento, por menor que seja, é um passo rumo à liberdade.','Pagar uma dívida é investir na sua paz e no seu futuro.','Pagar menos juros é como receber um aumento de salário.','Não deixe o ontem ocupar espaço demais no seu hoje.','Uma dificuldade também pode abrir uma oportunidade.','Aprender com um tropeço ajuda a dar o próximo passo.','Definir uma meta é começar a construir seu futuro.','Um passo de cada vez: hoje também conta.']};
for(const key of Object.keys(W)){W[key].motivations.push(...extra72[key]);Object.assign(W[key],{next:{es:'Otra frase',en:'Another thought',pt:'Outra frase'}[key],favorite:{es:'Guardar favorita',en:'Save favorite',pt:'Salvar favorita'}[key],favorited:{es:'Tu favorita',en:'Your favorite',pt:'Sua favorita'}[key]})}
const t=()=>W[language()];window.aryText72=t;
const persist76=(key,value)=>{try{localStorage.setItem(key,JSON.stringify(value));return true}catch(e){toast({es:'No se pudo guardar. Tu texto sigue aquí; vuelve a intentarlo.',en:'Could not save. Your text is still here; try again.',pt:'Não foi possível salvar. Seu texto continua aqui; tente novamente.'}[language()]);return false}};
const read=(key,fallback)=>{try{const value=JSON.parse(safeGet(key));return value===null?fallback:value}catch(e){return fallback}};
let ui=read(UI,{});const palettes=['season','ocean','violet','amber','forest'],sizes=[1,1.15,1.3,1.5];
const prefs=()=>({hidden:ui.hidden===true,size:sizes.includes(Number(ui.size))?Number(ui.size):1,palette:palettes.includes(ui.palette)?ui.palette:'season',brand:palettes.includes(ui.brand)?ui.brand:'season',contrast:ui.contrast===true});
window.aryHidden72=()=>prefs().hidden;
const moneyBefore=window.aryMoney63;window.aryMoney63=n=>aryHidden72()?'••••':moneyBefore(n);
const eye=off=>`<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="M2 12s3.5-7 10-7 10 7 10 7-3.5 7-10 7S2 12 2 12Z"/><circle cx="12" cy="12" r="3"/>${off?'<path d="m3 3 18 18"/>':''}</svg>`;
const headerBefore=window.aryHeaderActions64;window.aryHeaderActions64=()=>{const x=t(),hidden=aryHidden72();return headerBefore().replace('<div class="headerActions64">',`<div class="headerActions64"><button type="button" class="pill privacy72" aria-label="${hidden?x.show:x.hide}" title="${hidden?x.show:x.hide}" aria-pressed="${hidden}" onclick="aryTogglePrivacy72()">${eye(hidden)}<span class="eyeTooltip72">${hidden?x.show:x.hide}</span></button>`)};
window.aryTogglePrivacy72=()=>{ui.hidden=!aryHidden72();safeSet(UI,JSON.stringify(ui));render();applyPrivacy();toast(aryHidden72()?t().hidden:t().visible)};
window.arySetUI72=(key,value)=>{if(!['size','palette','brand','contrast'].includes(key))return;if(key==='size'&&!sizes.includes(Number(value)))return;if(key!=='size'&&key!=='contrast'&&!palettes.includes(value))return;ui[key]=key==='size'?Number(value):key==='contrast'?value==='true':value;safeSet(UI,JSON.stringify(ui));applyUI();};
window.aryResetUI72=()=>{ui={hidden:aryHidden72()};safeSet(UI,JSON.stringify(ui));applyUI();const p=prefs();for(const key of ['size','palette','brand']){const field=document.getElementById(key+'72');if(field)field.value=String(p[key])}const check=document.querySelector('#appearance72 input[type=checkbox]');if(check)check.checked=p.contrast};
function applyUI(){const p=prefs();document.body.style.setProperty('--ui-scale72',String(p.size));document.body.dataset.palette72=p.palette;document.body.dataset.brand72=p.brand;document.body.classList.toggle('private72',p.hidden);document.body.classList.toggle('highContrast72',p.contrast)}
const fields=new WeakMap(),textBefore=new Map();function applyPrivacy(){const hidden=aryHidden72();for(const el of document.querySelectorAll('#app input[inputmode="decimal"],#modal input[inputmode="decimal"]')){if(hidden){if(!fields.has(el))fields.set(el,{type:el.type,disabled:el.disabled});el.type='password';el.disabled=true;el.setAttribute('title',t().editAmounts)}else if(fields.has(el)){const p=fields.get(el);el.type=p.type;el.disabled=p.disabled;el.removeAttribute('title');fields.delete(el)}}
 if(hidden){for(const el of document.querySelectorAll('#app .ring b,#app .antStats26 strong,#app .privateValue72,#app .planStatus34 strong'))el.textContent='••••';for(const el of document.querySelectorAll('#app .chatBubble58,#app .chatMsg58'))el.textContent=el.textContent.replace(/\d+(?:[.,]\d+)*/g,'••••')}
 for(const root of document.querySelectorAll('#app,#modal .sheet')){const walker=document.createTreeWalker(root,NodeFilter.SHOW_TEXT);let node;while(node=walker.nextNode()){if(node.parentElement?.closest('input,textarea,select,option'))continue;if(hidden){const value=node.nodeValue||'',redacted=value.replace(/(?:[$€£¥₹]|USD|EUR|COP|BRL|R\$)\s*[-+]?\d[\d.,\s]*|[-+]?\d[\d.,\s]*\s*(?:USD|EUR|COP|BRL|%)/g,'••••');if(redacted!==value){if(!textBefore.has(node))textBefore.set(node,value);node.nodeValue=redacted}}else if(textBefore.has(node)){node.nodeValue=textBefore.get(node);textBefore.delete(node)}}}for(const node of textBefore.keys())if(!node.isConnected)textBefore.delete(node);
 const notice=document.querySelector('.privacyEditNote72');if(hidden&&document.querySelector('#modal input[inputmode="decimal"]')&&!notice){const el=document.createElement('p');el.className='privacyEditNote72 muted';el.textContent=t().editAmounts;document.querySelector('#modal .sheet')?.prepend(el)}else if(!hidden)notice?.remove();
}
const labels=()=>({home:{es:'Inicio',en:'Home',pt:'Início'},debts:{es:'Deudas',en:'Debts',pt:'Dívidas'},expenses:{es:'Gastos',en:'Expenses',pt:'Gastos'},plan:{es:'Plan',en:'Plan',pt:'Plano'},income:{es:'Ingresos',en:'Income',pt:'Renda'},ants:{es:'Gastos hormiga',en:'Small expenses',pt:'Pequenos gastos'},profile:{es:'Mi perfil',en:'My profile',pt:'Meu perfil'},calendar:{es:'Calendario',en:'Calendar',pt:'Calendário'},goals:{es:'Metas',en:'Goals',pt:'Metas'},progress:{es:'Progreso',en:'Progress',pt:'Progresso'},assistant:{es:'Asistente',en:'Assistant',pt:'Assistente'},buy:{es:'¿Puedo comprar esto?',en:'Can I buy this?',pt:'Posso comprar isso?'},more:{es:'Más',en:'More',pt:'Mais'},appearance:{es:t().access,en:t().access,pt:t().access},support:{es:t().support,en:t().support,pt:t().support},announcements:{es:t().announcements,en:t().announcements,pt:t().announcements},events:{es:t().events,en:t().events,pt:t().events},feedback:{es:t().feedback,en:t().feedback,pt:t().feedback}});
const normalize=q=>String(q||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().trim();
window.arySearchItems72=query=>{const q=normalize(query),out=Object.entries(labels()).map(([route,n])=>({name:n[language()],route,kind:'section'}));if(!aryHidden72()){for(const d of s.debts||[])out.push({name:d.name,route:'debts',kind:'debt',id:d.id});for(const e of s.expenses||[])out.push({name:e.name,route:'expenses',kind:'expense',id:e.id})}return out.filter(x=>!q||normalize(x.name).includes(q)).slice(0,24)};
window.arySearch72=()=>{const x=t();modal(`<h2>${x.search}</h2><label for="searchQuery72">${x.searchHint}</label><input id="searchQuery72" type="search" autocomplete="off" oninput="arySearchResults72(this.value)"><div id="searchResults72" class="searchResults72" aria-live="polite"></div><button type="button" class="btn widebtn" onclick="closeM()">${x.close}</button>`);arySearchResults72('');document.getElementById('searchQuery72')?.focus()};
let searchItems=[];window.arySearchResults72=query=>{searchItems=arySearchItems72(query);const host=document.getElementById('searchResults72');if(host)host.innerHTML=searchItems.length?searchItems.map((x,i)=>`<button type="button" class="btn searchResult72" onclick="arySearchOpen72(${i})"><span>${esc(x.name)}</span><small>${esc(labels()[x.route][language()])} →</small></button>`).join(''):`<p class="muted">${t().noResults}</p>`};
window.arySearchOpen72=i=>{const x=searchItems[i];if(!x)return;closeM();go(x.route);if(x.kind==='debt')debtForm(x.id);if(x.kind==='expense')expenseForm(x.id)};
document.addEventListener('keydown',event=>{if((event.ctrlKey||event.metaKey)&&event.key.toLowerCase()==='k'&&profile&&s.onboarded){event.preventDefault();arySearch72()}});
window.aryAppearance72=()=>{const x=t(),p=prefs(),select=(key,options)=>`<select id="${key}72" onchange="arySetUI72('${key}',this.value)">${options.map(([v,label])=>`<option value="${v}" ${String(p[key])===String(v)?'selected':''}>${esc(label)}</option>`).join('')}</select>`;modal(`<div id="appearance72"><h2>${x.access}</h2><label for="size72">${x.size}</label>${select('size',[[1,x.normal],[1.15,x.large],[1.3,x.larger],[1.5,x.largest]])}<label for="palette72">${x.colors}</label>${select('palette',palettes.map(v=>[v,x[v]]))}<label for="brand72">${x.brand}</label>${select('brand',palettes.map(v=>[v,x[v]]))}<label class="contrastChoice72"><input type="checkbox" ${p.contrast?'checked':''} onchange="arySetUI72('contrast',String(this.checked))"> ${x.contrast}</label><p class="appearancePreview72">Arydebts · ${x.note}</p><button type="button" class="btn widebtn" onclick="aryResetUI72()">${x.reset}</button><button type="button" class="btn primary widebtn" onclick="closeM()">${x.close}</button></div>`)};
const links=()=>[['appearance','⚙️',t().access],['support','💝',t().support],['announcements','📣',t().announcements],['events','🌍',t().events],['feedback','💬',t().feedback]];
const moreBefore=screens.more;screens.more=()=>moreBefore()+`<section class="moreWorkspace72"><button type="button" class="btn searchLaunch72" onclick="arySearch72()">⌕ ${t().search}</button><div class="communityGrid72">${links().map(([route,icon,name])=>`<button type="button" class="card communityLink72" onclick="go('${route}')"><span aria-hidden="true">${icon}</span><b>${name}</b><span aria-hidden="true">→</span></button>`).join('')}</div></section>`;
screens.appearance=()=>head(t().access)+`<section class="card full"><button class="btn primary widebtn" onclick="aryAppearance72()">${t().access}</button></section>`;
const settingsBefore=window.aryV18Settings;window.aryV18Settings=()=>{settingsBefore();const sheet=document.querySelector('#modal .sheet');if(!sheet)return;const button=document.createElement('button');button.type='button';button.className='btn widebtn';button.textContent='◐ '+t().access;button.onclick=aryAppearance72;sheet.insertBefore(button,sheet.querySelector('.signoutWave65')||sheet.lastElementChild)};
window.aryHomeProgress72=()=>{const x=t(),current=(s.debts||[]).reduce((n,d)=>n+Math.max(0,Number(d.balance)||0),0),paid=(s.payments||[]).reduce((n,p)=>n+Math.max(0,Number(p.amount)||0),0),total=current+paid,pct=total>0&&paid>0?Math.min(100,Math.round(paid/total*100)):null,hidden=aryHidden72();return `<button type="button" class="card full heroCard homeTruth29 homeTap51 progressCard72" onclick="go('debts')"><b>${x.progress}</b><div class="progressContent72"><div class="progressRing72" style="--progress72:${hidden?0:pct||0}%" aria-label="${x.inProgress}"><span class="privateValue72">${hidden?'••••':pct===null?'—':pct+'%'}</span></div><div><span class="muted">${x.start}</span><strong>${total>0?money(total):'—'}</strong><span class="muted">${x.remaining}</span><strong>${(s.debts||[]).length?money(current):'—'}</strong></div></div><small>${pct===null?x.emptyProgress:x.paid+' '+money(paid)}</small><div class="progressRibbon72" aria-hidden="true"></div></button>`};
window.arySaveNote72=()=>{const text=String(document.getElementById('selfNote72')?.value||'').trim().slice(0,240);if(!persist76(NOTE,text))return false;toast(t().saved);return true};
const profileBefore=window.aryProfile46;window.aryProfile46=()=>{profileBefore();const host=document.querySelector('.profileSection46');if(!host)return;const box=document.createElement('section');box.className='selfNoteEditor72';box.innerHTML=`<label for="selfNote72">${t().note}</label><textarea id="selfNote72" maxlength="240" placeholder="${esc(t().noteHint)}">${esc(read(NOTE,''))}</textarea><button type="button" class="btn widebtn" onclick="arySaveNote72()">${t().save}</button>`;host.after(box)};
window.aryCommitProfileNote75=()=>{const field=document.getElementById('selfNote72');if(field)safeSet(NOTE,JSON.stringify(String(field.value||'').trim().slice(0,240)))};
const profilePageBefore=screens.profile;screens.profile=()=>profilePageBefore()+`<section class="card full selfMessage72"><b>✨ ${t().note}</b><p>${esc(read(NOTE,'')||t().motivations[0])}</p><button type="button" class="btn" onclick="aryProfile46()">${t().save}</button></section>`;
const safeUrl=raw=>{try{const u=new URL(raw);return u.protocol==='https:'&&!u.username&&!u.password?u.href:''}catch(e){return''}};
screens.support=()=>{const x=t(),url=safeUrl(window.aryUIConfig72?.donationUrl);return head(x.support,x.supportSub)+`<section class="card full support72"><span class="supportHeart72" aria-hidden="true">♡</span><h2>Arydebts</h2><p>${x.free}</p>${url?`<a class="btn primary widebtn" href="${esc(url)}" target="_blank" rel="noopener noreferrer">${x.donate} ↗</a>`:`<p class="muted">${x.soon}</p>`}<button type="button" class="btn widebtn" onclick="go('feedback')">💬 ${x.feedback}</button></section>`};
screens.announcements=()=>head(t().announcements)+`<section class="card full"><div class="releaseBadge72">ARYDEBTS · V77</div>${t().updates.map(message=>`<p class="announcement72">✦ ${message}</p>`).join('')}<button class="btn" onclick="aryAppearance72()">${t().access}</button></section>`;
window.aryEvents72=(now=new Date(),locale=s.locale)=>{const year=now.getFullYear(),begin=new Date(year,now.getMonth(),now.getDate()),x=t(),events=[{month:1,day:1,name:x.newyear,icon:'✨'},{month:10,day:31,name:x.halloween,icon:'🎃'},{month:12,day:25,name:x.christmas,icon:'🎄'}];if(locale.endsWith('-US'))events.push({month:7,day:4,name:x.independence+' · 🇺🇸',icon:'🇺🇸',url:'https://www.usa.gov/holidays'});if(locale==='es-CO')events.push({month:7,day:20,name:x.independence+' · 🇨🇴',icon:'🇨🇴',url:'https://www.banrep.gov.co/es/feriado-bancario/dia-independencia-colombia-2025'});if(locale==='pt-BR')events.push({month:9,day:7,name:x.independence+' · 🇧🇷',icon:'🇧🇷',url:'https://www.gov.br/turismo/pt-br/assuntos/noticias/sete-de-setembro-destinos-nacionais-para-curtir-o-feriado-da-independencia'});return events.map(e=>{let date=new Date(year,e.month-1,e.day);if(date<begin)date=new Date(year+1,e.month-1,e.day);return{...e,date:date.getFullYear()+'-'+String(e.month).padStart(2,'0')+'-'+String(e.day).padStart(2,'0')}}).sort((a,b)=>a.date.localeCompare(b.date))};
screens.events=()=>head(t().events,t().annual)+`<section class="card full"><div class="list">${aryEvents72().map(e=>`<div class="eventCard72"><span aria-hidden="true">${e.icon}</span><div><b>${esc(e.name)}</b><p>${esc(fmtDate(e.date))}</p></div>${e.url?`<a class="btn tiny" href="${esc(e.url)}" target="_blank" rel="noopener noreferrer">${t().source} ↗</a>`:''}</div>`).join('')}</div><button class="btn widebtn" onclick="go('calendar')">${t().calendar}</button><a class="btn widebtn" href="https://www.nasa.gov/events/" target="_blank" rel="noopener noreferrer">${t().space} ↗</a></section>`;
let comments=read(FEEDBACK,[]);if(!Array.isArray(comments))comments=[];comments=comments.filter(c=>c&&Number.isSafeInteger(c.id)&&c.id>0&&typeof c.text==='string').map(c=>({id:c.id,text:c.text.slice(0,1000),date:typeof c.date==='string'?c.date:''}));
window.arySaveFeedback72=()=>{const text=String(document.getElementById('feedbackText72')?.value||'').trim().slice(0,1000);if(!text)return;const id=Math.max(Date.now(),...comments.map(c=>c.id+1));if(!Number.isSafeInteger(id))return;const next=[{id,text,date:localDate()},...comments].slice(0,20);if(!persist76(FEEDBACK,next))return false;comments=next;save();toast(t().saved);return true};
window.aryDeleteFeedback72=id=>{const next=comments.filter(c=>c.id!==id);if(!persist76(FEEDBACK,next))return false;comments=next;render();return true};
window.aryPrepareFeedback72=id=>{const comment=comments.find(c=>c.id===id);if(!comment)return;const url='https://github.com/Juanpachangga/arydebts-solution/issues/new?title='+encodeURIComponent('Arydebts feedback')+'&body='+encodeURIComponent(comment.text);modal(`<h2>${t().feedback}</h2><p>${t().feedbackReview}</p><blockquote>${esc(comment.text)}</blockquote><a class="btn primary widebtn" href="${esc(url)}" target="_blank" rel="noopener noreferrer">${t().shareComment} ↗</a><button class="btn widebtn" onclick="closeM()">${t().close}</button>`)};
screens.feedback=()=>head(t().feedback)+`<section class="card full"><label for="feedbackText72">${t().feedbackHint}</label><textarea id="feedbackText72" maxlength="1000"></textarea><button type="button" class="btn primary widebtn" onclick="arySaveFeedback72()">${t().saveComment}</button><p class="muted">${t().localFeedback}</p></section><section class="card full"><div class="list">${comments.length?comments.map(c=>`<article class="feedbackCard72"><p>${esc(c.text)}</p><small>${esc(fmtDate(c.date))}</small><div class="rowActions"><button class="btn" onclick="aryPrepareFeedback72(${c.id})">${t().shareComment}</button><button class="btn dangerBtn" onclick="aryDeleteFeedback72(${c.id})">${t().delete}</button></div></article>`).join(''):`<p class="muted">${t().emptyFeedback}</p>`}</div></section>`;
window.aryLandingQuotes74=(date=new Date())=>{const weeks=Math.floor((Date.UTC(date.getFullYear(),date.getMonth(),date.getDate())-Date.UTC(2026,0,5))/604800000),pairs=Math.floor(t().motivations.length/2),i=((weeks%pairs)+pairs)%pairs*2;return [t().motivations[i],t().motivations[i+1]]};
function refreshLandingQuotes74(){const box=document.querySelector('.motivation72');if(screen!=='welcome'||!box)return;const next=aryLandingQuotes74().map((message,i)=>`<p class="${i===0?'motivationMain72':''}">${esc(message)}</p>`).join('');if(box.innerHTML!==next)box.innerHTML=next}
function scheduleQuotes74(){const now=new Date(),next=new Date(now);next.setHours(24,0,2,0);setTimeout(()=>{refreshLandingQuotes74();scheduleQuotes74()},next-now)}
window.addEventListener('focus',refreshLandingQuotes74);document.addEventListener('visibilitychange',()=>{if(!document.hidden)refreshLandingQuotes74()});scheduleQuotes74();
function enhance(){applyUI();applyPrivacy();paintHeaderQuote72();const host=document.getElementById('app');if(!host)return;if(profile&&s.onboarded&&['home','debts','expenses','plan','more'].includes(screen)&&!host.querySelector('.searchLaunch72')){const button=document.createElement('button');button.type='button';button.className='btn searchLaunch72';button.textContent='⌕ '+t().search;button.onclick=arySearch72;host.querySelector('.hello')?.after(button)}if(screen==='home'){const coach=host.querySelector('.homeCoach29');if(coach)paintQuote72()}if(screen==='welcome'){const footer=host.querySelector('.trust55');if(footer&&!footer.querySelector('.motivation72')){footer.querySelector('small')?.remove();const section=document.createElement('div');section.className='motivation72';section.innerHTML=aryLandingQuotes74().map((message,i)=>`<p class="${i===0?'motivationMain72':''}">${esc(message)}</p>`).join('');footer.appendChild(section)}}}
function paintHeaderQuote72(){if(!['home','debts','expenses','plan','more','progress','ants'].includes(screen))return;const subtitle=document.querySelector('.hello>.muted');if(subtitle)subtitle.textContent=(quoteIndex72===null&&read(quoteKey72,-1)===-1?read(NOTE,''):'')||t().motivations[quoteIndex()]}
let quoteIndex72=null;
const quoteKey72='ary-favorite-quote-v72';
const quoteIndex=()=>quoteIndex72===null?Math.max(0,Math.min(t().motivations.length-1,Number(read(quoteKey72,new Date().getDate()%t().motivations.length))||0)):quoteIndex72;
function paintQuote72(){paintHeaderQuote72();const coach=document.querySelector('.homeCoach29');if(!coach)return;const i=quoteIndex(),favorite=read(quoteKey72,-1)===i;const focused=document.activeElement?.closest?.('.quoteActions72 button')?.dataset.quoteAction;coach.onclick=null;coach.onkeydown=null;coach.removeAttribute('onclick');coach.removeAttribute('tabindex');coach.removeAttribute('role');coach.classList.remove('tap45');coach.innerHTML='<b aria-live="polite">✨ '+esc((quoteIndex72===null&&read(quoteKey72,-1)===-1?read(NOTE,''):'')||t().motivations[i])+'</b><div class="quoteActions72"><button type="button" class="btn" data-quote-action="next" onclick="aryNextQuote72(event)">↻ '+t().next+'</button><button type="button" class="btn" aria-pressed="'+favorite+'" data-quote-action="favorite" onclick="aryFavoriteQuote72(event)">'+(favorite?'★ '+t().favorited:'☆ '+t().favorite)+'</button></div>';if(focused)coach.querySelector('[data-quote-action="'+focused+'"]')?.focus()}
window.aryNextQuote72=event=>{event?.preventDefault();event?.stopPropagation();quoteIndex72=(quoteIndex()+1)%t().motivations.length;paintQuote72()};
window.aryFavoriteQuote72=event=>{event?.preventDefault();event?.stopPropagation();safeSet(quoteKey72,JSON.stringify(quoteIndex()));paintQuote72();toast(t().saved)};
const before=window.render;window.render=()=>{const result=before();enhance();return result};const modalBefore=window.modal;window.modal=html=>{const result=modalBefore(html);applyPrivacy();return result};render();
})();
